== Requirement Class "Tiles from more than one collection"

=== Overview

[[tiles-collections-overview]]

include::requirements/tiles/requirements_class_collections.adoc[]

In previous clauses tiles that are produced from one, and only one resource were discussed. This scenario is achieved by concatenating the tile path to a resource (e.g. a feature collection). This requirements class is an extension of the core requirements class that defines how to create tiles that combine more than one resource. This is achieved by having the tile path also available at the root of the service.

=== API landing page

The landing page provides links to start exploring the resources offered by the API. It mainly consists of a list of links. The core of this draft specification does not add anything to the links required by OGC API - Common. This requirements class for _tiles from more than one collection_ requires a new link for getting the description of the _tiles from more than one collection_ on top of the common ones.

==== Response

include::requirements/tiles/collections/REQ_root-success.adoc[]

In the landing page, in JSON format, the links follow the link schema defined in the OGC API - Common. Below is an example fragment of the response to an OGC API - Tiles landing page showing the new link.

[[landingPageTilesCollections]]
.API Landing Page fragment that advertises the path to get tiles for more than one collection
=================
[source,JSON]
----
{
  links: [
    ...,
    {
       "href": "http://data.example.org/tiles",
       "rel": "tiles",
       "type": "application/json",
       "title": "Link to information on map tiles combining more than one collection",
    }
  ]
}
----
=================

=== Declaration of conformance classes

==== Response

The conformance page mainly consists of a list of links. OGC API - Common already requires some links.

include::requirements/tiles/collections/REQ_conformance-success.adoc[]

On the conformance page (typically in JSON format) the links follow the link schema defined in the OGC API – Common draft specification. The following is an example fragment from the response to an OGC API - Tiles conformance information page showing the support for _tiles from more than one collection_

[[ConformancePageTilesCollections]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/core"
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/collections"
  ]
}
=================

=== Tiles description
The response to the tiles description operation contains the necessary information to later formulate a tile request of tiles from more than one collection.

==== Operation

include::requirements/tiles/collections/REQ_ts-op.adoc[]

The request of this operation has no parameters.

==== Response
A successful response to a tiles request for more than one collection will respond with a data structure with specific information necessary to get tiles representing the resource collection. In this requirements class, the response only provides the URL template to retrieve a tile.

include::requirements/tiles/collections/REQ_ts-tile-examples.adoc[]

One common order used in URL templates for tiles is: /tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}. However, this draft specification allows for other URL template composition.

[#URL_template_tile_collections,reftext='{table-caption} {counter:table-num}']
.URI template variables for tiles and possible values
[cols="30,35,70",options="header"]
!===
|URL template variable |Meaning |Possible values
|TileMatrixSetId |tile matrix set identifier |The identifiers included in Annex D of OGC 17-083r2 or defined by extensions of the core requirements class.
|TileMatrix |tile matrix identifier |Identifier of the tile matrix (representing a zoom level, a.k.a. a scale) listed in the TileMatrixSet definition
|TileRow |row index of tile matrix	|A non-negative integer between 0 and the MatrixHeight – 1. If there is a TileMatrixSetLimits the value is limited between MinTileRow and MaxTileRow
|TileCol |column index of tile matrix	|A non-negative integer between 0 and the MatrixWidth – 1. If there is a TileMatrixSetLimits the value is limited between MinTileCol and MaxTileCol
!===

.API tiles response fragment with the link to retrieve tiles form more than one collection
=================
[source,JSON]
links:
[
    {
      "href": "http://data.example.com/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}",
      "rel": "item",
      "type": "image/png",
    }
]
=================

In general, the `tileMatrixSetLinks` and the `tileMatrixSetLimits` can be determined by examining this information in the individual collections. In some cases, the server could also include the `tileMatrixSetLinks` data structure as part of the response to this operation. Clients should be prepared to determine if a `tileMatrixSetLinks` data structure is not provided in certain combinations of collections by examining the tileMatrixSet values and limits from the information in the individual collections and calculating the limits as the most restrictive intersection of them.

=== Tiles from more than one collection
This operation allows retrieving a single tile that represents information coming from more than one collection.

==== Operation
include::requirements/tiles/collections/REQ_tcs-op.adoc[]

==== Parameter tileMatrixSetId
include::requirements/tiles/collections/REQ_tcs-tilematrixsetid-definition.adoc[]

==== Parameter tileMatrix
include::requirements/tiles/collections/REQ_tcs-tilematrix-definition.adoc[]

==== Parameter tileRow
include::requirements/tiles/collections/REQ_tcs-tilerow-definition.adoc[]

==== Parameter tileCol
include::requirements/tiles/collections/REQ_tcs-tilecol-definition.adoc[]

==== Parameter Collections
include::requirements/tiles/collections/REQ_tcs-collections-definition.adoc[]

include::recommendations/tiles/collections/REC_tcs-collections-definition.adoc[]

include::recommendations/tiles/collections/PER_tcs-collections-definition.adoc[]

==== Response
A successful response to a tile request is consistent with the media type of resource requested. This draft specification does not impose any media type. For example, for features the media type can be GeoJSON or Mapbox vector tiles,for coverages it may be a GeoTIFF, and for maps it may be a JPEG or a PNG.

include::requirements/tiles/collections/REQ_tcs-success.adoc[]

==== Error conditions
If the value of the parameter `tileMatrixSetId` is not available by the server for this resource or the values of the parameters `tileMatrix`, `tileRow`, `tileCol` are out-of-range, the status code of the response is 404.

If the value of the parameter `collections` contains a collection id that does not exist on the server, the status code of the response is 404.

If the value of the parameter `collections` has a wrong format or combines collections and some of them are not compatible with the `tileMatrixSetId` value, the status code of the response is 500.
