[[ats_geojson_content]]
////
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/geojson/content*
^|Test Purpose |Validate the particularities of a GeoJSON response
^|Requirement |/req/geojson/content
^|Test Method |1. Validate that every 200-response of the server with the media type application/geo+json contains a GeoJSON document representing only one tile.

2. Validate that root of the GeoJSON document is a GeoJSON FeatureCollection Object for features, or a GeoJSON Feature Object for a single feature.

3. Validate that regardless of the TileMatrixSet CRS, the geometry coordinates are in CRS84 as stated in the GeoJSON standard unless a _prior arrangement_ applies to use an alternative coordinate reference system. The fact that a TileMatrixSet is used does not constitute a _prior arrangement_. For example, an extension could negotiate another CRS for coordinates with a query parameter.
|===
////

[abstract_test]
====
[%metadata]
identifier:: /conf/geojson/content
target:: /req/geojson/content
test-purpose:: Validate the particularities of a GeoJSON response
test-method::
+
--
1. Validate that every 200-response of the server with the media type application/geo+json contains a GeoJSON document representing only one tile.

2. Validate that root of the GeoJSON document is a GeoJSON FeatureCollection Object for features, or a GeoJSON Feature Object for a single feature.

3. Validate that regardless of the TileMatrixSet CRS, the geometry coordinates are in CRS84 as stated in the GeoJSON standard unless a _prior arrangement_ applies to use an alternative coordinate reference system. The fact that a TileMatrixSet is used does not constitute a _prior arrangement_. For example, an extension could negotiate another CRS for coordinates with a query parameter.
--
====
