[[req_collections-selection_query-collections]]
////
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/collections-selection/query-collections*
^|A |An operation that acts on a resource consisting of multiple geospatial data sub-resources (e.g., a resource derived from a root dataset) SHALL support an optional parameter `collections` with the following characteristics (shown as OpenAPI Specification 3.0 fragment)
[source,YAML]
----
  name: collections
  in: query
  required: false
  style: form
  explode: false
  schema:
    type: array
    items:
      type: string
----
^|B |The parameter `collections` SHALL be supported by tileset resources and tiles resources for origins consisting of multiple geospatial data sub-resources (e.g. dataset tileset at `{datasetAPI}/tiles/WebMercatorQuad` and dataset tiles at `{datasetAPI}/tiles/WebMercatorQuad/{tileMatrix}/{tileRow}/{tileCol}`).
^|C |Implementations SHALL support a comma-separated list of either geospatial resource identifiers (e.g., collectionId's) and/or full URLs to geospatial resource identifiers.
|===
////


[requirement,label="/req/collections-selection/query-collections",identifier="/req/collections-selection/query-collections"]
====

[.component,class=part]
--
An operation that acts on a resource consisting of multiple geospatial data sub-resources (e.g., a resource derived from a root dataset) SHALL support an optional parameter `collections` with the following characteristics (shown as OpenAPI Specification 3.0 fragment)
[source,YAML]
----
  name: collections
  in: query
  required: false
  style: form
  explode: false
  schema:
    type: array
    items:
      type: string
----

--

[.component,class=part]
--
The parameter `collections` SHALL be supported by tileset resources and tiles resources for origins consisting of multiple geospatial data sub-resources (e.g., dataset tileset at `{datasetAPI}/tiles/WebMercatorQuad` and dataset tiles at `{datasetAPI}/tiles/WebMercatorQuad/{tileMatrix}/{tileRow}/{tileCol}`).
--

[.component,class=part]
--
Implementations SHALL support a comma-separated list of either geospatial resource identifiers (e.g., collectionId's) and/or full URLs to geospatial resource identifiers.
--

====
