== Requirement Class "Tiles Info"

=== Overview

NOTE: This section should be elaborated by a SWG and only some hints are provided in this Engineering Report

WARNING: Some subsections are intentionally left blank.

[[tiles-info-overview]]
include::requirements/tiles/requirements_class_info.adoc[]

This requirements calls makes data contained in tiles a little more informative than just "nice pictures" by allowing clients to implement a click user event. By clicking on a pixel in the screen that shows a tile, the user will receive some textual information describing what is shown in that pixel. For example, by clicking on a tile containing elevation data the user will get the elevation value.

NOTE: The use of `pixel in the screen` can create the wrong impression that this operation is restricted to "raster based tiles". This is not necessarily true. The Two Dimensional Tile Matrix Set standard (OGC 17-083r2) discusses how tile matrices are created for an optimum resolution in the screen, even if they might be entirely feature based.

When fully completed, the new OGC API architecture should be able to integrate several representations of the same resource. This way a digital elevation model could be accessible as a tile and also as a coverage. The coverage part should be able to provide elevation values to the client. When that day arrives, this info requirements class will no longer be needed as the coverage functionality will provide the client with enough data to emulate this extension and some other extra interactions such us the capability to create vertical profiles.

=== Overview

[[core-overview]]

TBD

//include::requirements/tiles/requirements_class_info.adoc[]

=== Declaration of conformance classes

==== Response

The conformance page mainly consists of a list of links. OGC API - Common already requires some links.

//include::requirements/tiles/info/REQ_conformance-success.adoc[]

In the conformance page (typically in JSON format) the links follow the link schema defined in the OGC API - Common. The following is an example fragment of the response to an OGC API - Tiles conformance information page.

[[ConformancePageTilesInfo]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/info"
  ]
}
=================


=== Collection
This draft specification includes dependencies on OGC API - Common collection. The response to the operation is extended with the necessary information to formulate a tile response for this collection.

==== Collection Links


//include::recommendations/tiles/info/REC_sfc-tile-examples.adoc[]

.API collection response fragment
=================
[source,JSON]
links:
[
    {
      "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad/0/0/0",
      "rel": http://www.opengis.net/def/rel/OGC/1.0/tiles",
      "type": "image/png"
    },
    {
      "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad/0/0/0/info",
      "rel": "http://www.opengis.net/def/rel/OGC/1.0/attributes",
      "type": "text/html"
    }
]
=================

=== FeatureInfo

Implementations of the OGC API – Maps and Tiles draft specification may support requests for information about the features present at a particular pixel location in the screen on a map tile. Requests for feature information will specify the tile along with a pixel location on that tile. The server will provide information on the features present at or near the location specified by the client request. The server may choose what information to provide about the nearby features.

==== FeatureInfo document

A FeatureInfo document is the resource representation of a FeatureInfo resource in resource oriented architectural style. The FeatureInfo document SHALL be in the format specified in the request when that format has been advertised in the *ServiceMetadata document* as available for that FeatureInfo resource.

For better interoperability between servers and clients, the Simple Features Profile of the Geography Markup Language (GML) [06-049r1] as a supported document format for FeatureInfo resources is recommended. The Simple Features Profile of GML defines three levels of content in three profiles with different degrees of constraints to the GML flexibility. Support for the most constrained one (level 0) that results in a simpler GML document is strongly recommended. In the context of that profile only simple XML types can be used as thematic properties and cardinality greater than one is not allowed. Servers and clients SHALL specify the MIME type "application/gml+xml; version=3.1" as an InfoFormat value and the GML application schema of the response SHOULD conform to GML Simple Features profile level 0 when that GML profile is used. In most cases, only thematic attributes of the features are intended to be included in a FeatureInfo document but the Simple Features profiles were evidently intended to include the geometric information of the features in the GML objects. However, an application schema can be generated that does not include feature geometry and only describes non-geometric feature attribute types. This can be very useful to avoid unnecessarily requesting long sequences of position values in line or polygon layers.

Also, to allow easy presentation of the data, support for the HTML format (represented by an InfoFormat MIME type of "text/html") is also recommended.
