[appendix]
:appendix-caption: Annex
[[Bibliography]]
= Bibliography

This standard is deeply inspired in concepts defined in the following documents that preceeded it. This standard offers and alternative interface to fulfill similar tasks included in these references:

* OGC: OGC 07-057, OpenGIS® Web Map Tile Service Implementation Standard (2010)
* OGC: OGC 13-082, OGC® Web Map Tile Service (WMTS) Simple Profile (2016)
* OGC and ISO: OGC 06-042 1.3.0	OpenGIS Web Map Service (WMS) Implementation Specification

This standard is deeply inspired in concepts and techniques defined in the following OGC API documents. Implementations of this standard can be done also following one of them:

* OGC: OGC 19-072, OGC API - Common Part 1: core
* OGC: OGC 17-069r3, OGC API - Features Part 1

Many ideas standard used in this standard where tested in Testbed 15 and experiences where documented here:
* OGC: OGC 19-069, OGC Testbed-15: Maps and Tiles API Engineering Report

The OGC API standards are considering ideas, methods and practices extracted from:
* [[SDWBP]] W3C/OGC: Spatial Data on the Web Best Practices, W3C Working Group Note 28 September 2017, https://www.w3.org/TR/sdw-bp/
* [[DWBP]] W3C: Data on the Web Best Practices, W3C Recommendation 31 January 2017, https://www.w3.org/TR/dwbp/
* [[DCAT]] W3C: Data Catalog Vocabulary, W3C Recommendation 16 January 2014, https://www.w3.org/TR/vocab-dcat/
* [[link-relations]] IANA: Link Relation Types, https://www.iana.org/assignments/link-relations/link-relations.xml
* [[MVT]] Mapbox: Mapbox Vector Tiles Specification, https://docs.mapbox.com/vector-tiles/specification/
