[bibliography]
== References

The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

* [[[ogc19-014r3,OGC 19-014r3]]], OGC Abstract Specification Topic 22 - Core Tiling Conceptual and Logical Models for 2D Euclidean Space, 2020
* [[[ogc17-083r4,OGC 17-083r4]]], OGC Two Dimensional Tile Matrix Set and Tile Set Metadata (2022)
* [[[OGC19-072,OGC 19-072]]] Charles Heazel: OGC API - Common - Part 1: Core (Draft). OGC 19-072, Open Geospatial Consortium, http://docs.ogc.org/DRAFTS/19-072.html[http://docs.ogc.org/DRAFTS/19-072.html]
* [[[OGC20-024,OGC 20-024]]] Charles Heazel: OGC API - Common - Part 2: Geospatial Data (Draft). OGC 20-024, Open Geospatial Consortium, http://docs.ogc.org/DRAFTS/20-024.html[http://docs.ogc.org/DRAFTS/20-024.html]

NOTE: Certain conformance classes have a dependency on OGC API - Common - Part 1: Core
or OGC API - Common - Part 2: Geospatial data. In some cases, it is possible to replace these dependencies with http://docs.ogc.org/is/17-069r3/17-069r3.html[OGC 17-069r3] OGC API - Features - Part 1: Core.
