[[rc_oas30_definition]]
== Requirements Class "OpenAPI Specification 3.0"

=== Overview

include::requirements/requirements_class_oas30.adoc[]

The OpenAPI 3.0 Requirements Class details providing a definition of a Web API implementing the OGC API - Tiles Standard using the OpenAPI Specification version 3.0.

=== Web API OpenAPI description

The OpenAPI definition provides a description of the complete list of API resources. Reading this description, an application would have the full picture of the resources that the API provides, how to retrieve them, and what responses are expected for successful and unsuccessful requests. Without this API description an application would be forced to traverse all links, starting with the landing page, to get an equivalent full list of resources.

The (_oas30_) requirement class from _OGC API - Common - Part 1: Core_ provides many details on general requirements that this requirements class adopts by dependency. In addition, extra requirements are provided. Also, the _OGC API - Common_ requirements class provides details on how to request an API definition.

==== Response

===== Completeness
The OpenAPI definition resulting as a response of this request needs to take into consideration the relevant resources specified in this standard.

include::requirements/oas30/REQ_completeness.adoc[]

===== Reusable API components

Reusable components for creating OpenAPI definitions for implementations of this OGC API can be found in http://schemas.opengis.net/ogcapi/tiles/part1/1.0/openapi

////
NOTE: While this specification is in draft status, the components are available from https://github.com/opengeospatial/ogcapi-tiles/tree/master/openapi .
////


A server implementation of the OGC API - Tiles Standard can use the content in the openapi folder in https://schemas.opengis.net/ogcapi/tiles/part1/1.0 to generate a response for the openapi description. The http://schemas.opengis.net/ogcapi/tiles/part1/1.0/openapi/ogcapi-tiles-1.yaml[ogcapi-tiles-1.yaml] file includes paths and components. An implementation should only include the paths that are implemented and remove the references to the rest. The components part includes parameters, responses and schemas that can be reused as-is. The `api` folder (https://schemas.opengis.net/ogcapi/tiles/part1/1.0/openapi/api/) contains JSON files that are templates with enumerated values for collections (all, coverages or vector), styles, tileMatrixSets. A particular implementation of this API should enumerate the actual resources exposed by the API in the same way. The server can select to dynamically implement responses to /api/* (where * is replaced by all-collections, styles, ... ) or hardcode the /api/* files with the actual list of resource identifiers in the enumerations.

To improve performance, the whole content of this folder can be bundled into a single document by executing a tool such as _swagger-cli_. This can be served for the OGC API - Common - Part 1 `service-desc` link from the landing page.

===== Path Operation Ids

The OpenAPI definition provides to a client application a set of paths that the client can use to interact with the API and get new resources. The OpenAPI description of each path provides a description of what parameters to use in the request and what to expect in the response. However, this standard is not proposing a fixed set of paths so there is an issue identifying the requirements classes pertaining to each path in an API instance. In other words, the OpenAPI description alone does not provide enough information by itself and there is a need to identify the requirements classes pertaining to a resource (a path) and complete the information necessary for the client to implement the necessary logic to generate the request and understand the response. This standard proposes a suffix mechanism to be applied to the `operationId` property of the path to list the requirement classes pertaining to each path. Each path should have a unique operationId suffix, so it is expected that the OpenAPI instance provides a prefix to the proposed suffixes that make each operationId unique.

include::requirements/oas30/REQ_operation-id.adoc[]

[#openapi-operation-id-suffixes,reftext='{table-caption} {counter:table-num}']
.OpenAPI operationId suffixes
[width = "100%",options="header",cols="12%,8%,12%,15%,53%"]
|===
|Origin          |Styled   |Data Type    |Resource       |_operationId_ suffixes^1^
5+|_With the resource types and origins described in this document_
|DataSet^6^      |         |Vector       |TileSetsList^5^|`.dataset.vector.getTileSetsList`
|DataSet^6^      |         |Vector       |TileSet^4^     |`.dataset.vector.getTileSet`
|DataSet^6^      |         |Vector       |Tile^3^        |`.dataset.vector.getTile`
|DataSet^6^      |Styled^8^|Vector       |TileSetsList^5^|`.dataset.style.vector.getTileSetsList`
|DataSet^6^      |Styled^8^|Vector       |TileSet^4^     |`.dataset.style.vector.getTileSet`
|DataSet^6^      |Styled^8^|Vector       |Tile^3^        |`.dataset.style.vector.getTile`
|DataSet^6^      |         |Map^10^      |TileSetsList^5^|`.dataset.map.getTileSetsList`
|DataSet^6^      |         |Map^10^      |TileSet^4^     |`.dataset.map.getTileSet`
|DataSet^6^      |         |Map^10^      |Tile^3^        |`.dataset.map.getTile`
|DataSet^6^      |Styled^8^|Map^10^      |TileSetsList^5^|`.dataset.style.map.getTileSetsList`
|DataSet^6^      |Styled^8^|Map^10^      |TileSet^4^     |`.dataset.style.map.getTileSet`
|DataSet^6^      |Styled^8^|Map^10^      |Tile^3^        |`.dataset.style.map.getTile`
|Collection^7^   |         |Vector       |TileSetsList^5^|`.collection.vector.getTileSetsList`
|Collection^7^   |         |Vector       |TileSet^4^     |`.collection.vector.getTileSet`
|Collection^7^   |         |Vector       |Tile^3^        |`.collection.vector.getTile`
|Collection^7^   |Styled^8^|Vector       |TileSetsList^5^|`.collection.style.vector.getTileSetsList`
|Collection^7^   |Styled^8^|Vector       |TileSet^4^     |`.collection.style.vector.getTileSet`
|Collection^7^   |Styled^8^|Vector       |Tile^3^        |`.collection.style.vector.getTile`
|Collection^7^   |         |Coverage^9^  |TileSetsList^5^|`.collection.coverage.getTileSetsList`
|Collection^7^   |         |Coverage^9^  |TileSet^4^     |`.collection.coverage.getTileSet`
|Collection^7^   |         |Coverage^9^  |Tile^3^        |`.collection.coverage.getTile`
|Collection^7^   |         |Map^10^      |TileSetsList^5^|`.collection.map.getTileSetsList`
|Collection^7^   |         |Map^10^      |TileSet^4^     |`.collection.map.getTileSet`
|Collection^7^   |         |Map^10^      |Tile^3^        |`.collection.map.getTile`
|Collection^7^   |Styled^8^|Map^10^      |TileSetsList^5^|`.collection.style.map.getTileSetsList`
|Collection^7^   |Styled^8^|Map^10^      |TileSet^4^     |`.collection.style.map.getTileSet`
|Collection^7^   |Styled^8^|Map^10^      |Tile^3^        |`.collection.style.map.getTile`
5+|_With other potential resource types_
|DataSet^6^      |         |_other_      |TileSetsList^5^|`.dataset.*.getTileSetsList`
|DataSet^6^      |         |_other_      |TileSet^4^     |`.dataset.*.getTileSet`
|DataSet^6^      |         |_other_      |Tile^3^        |`.dataset.*.getTile`
|DataSet^6^      |Styled^8^|_other_      |TileSetsList^5^|`.dataset.style.*.getTileSetsList`
|DataSet^6^      |Styled^8^|_other_      |TileSet^4^     |`.dataset.style.*.getTileSet`
|DataSet^6^      |Styled^8^|_other_      |Tile^3^        |`.dataset.style.*.getTile`
|Collection^7^   |         |_other_      |TileSetsList^5^|`.collection.*.getTileSetsList`
|Collection^7^   |         |_other_      |TileSet^4^     |`.collection.*.getTileSet`
|Collection^7^   |         |_other_      |Tile^3^        |`.collection.*.getTile`
|Collection^7^   |Styled^8^|_other_      |TileSetsList^5^|`.collection.style.*.getTileSetsList`
|Collection^7^   |Styled^8^|_other_      |TileSet^4^     |`.collection.style.*.getTileSet`
|Collection^7^   |Styled^8^|_other_      |Tile^3^        |`.collection.style.*.getTile`
5+|_With other potential origins_
|_other_         |         |Vector       |TileSetsList^5^|`#.vector.getTileSetsList`
|_other_         |         |Vector       |TileSet^4^     |`#.vector.getTileSet`
|_other_         |         |Vector       |Tile^3^        |`#.vector.getTile`
|_other_         |Styled^8^|Vector       |TileSetsList^5^|`#.style.vector.getTileSetsList`
|_other_         |Styled^8^|Vector       |TileSet^4^     |`#.style.vector.getTileSet`
|_other_         |Styled^8^|Vector       |Tile^3^        |`#.style.vector.getTile`
|_other_         |         |Coverage^9^  |TileSetsList^5^|`#.coverage.getTileSetsList`
|_other_         |         |Coverage^9^  |TileSet^4^     |`#.coverage.getTileSet`
|_other_         |         |Coverage^9^  |Tile^3^        |`#.coverage.getTile`
|_other_         |         |Map^10^      |TileSetsList^5^|`#.map.getTileSetsList`
|_other_         |         |Map^10^      |TileSet^4^     |`#.map.getTileSet`
|_other_         |         |Map^10^      |Tile^3^        |`#.map.getTile`
|_other_         |Styled^8^|Map^10^      |TileSetsList^5^|`#.style.map.getTileSetsList`
|_other_         |Styled^8^|Map^10^      |TileSet^4^     |`#.style.map.getTileSet`
|_other_         |Styled^8^|Map^10^      |Tile^3^        |`#.style.map.getTile`
|_other_         |         |_other_      |TileSetsList^5^|`#.*.getTileSetsList`
|_other_         |         |_other_      |TileSet^4^     |`#.*.getTileSet`
|_other_         |         |_other_      |Tile^3^        |`#.*.getTile`
|_other_         |Styled^8^|_other_      |TileSetsList^5^|`#.style.*.getTileSetsList`
|_other_         |Styled^8^|_other_      |TileSet^4^     |`#.style.*.getTileSet`
|_other_         |Styled^8^|_other_      |Tile^3^        |`#.style.*.getTile``
5+|^1^ '*' represents a _resource type_ to be defined in another relevant standard. '#' represents an optional _origin_ that could be defined in another relevant standard.


^2^ The suffixes derived from these resource types are not required by this standard and will be proposed by the relevant standard defining them.


^3^ The _Tile_ resource is defined in <<rc_tiles_core>>.


^4^ The _TileSet_ resource is defined in <<rc_tileSet>>.


^5^ The _TileSetsList_ resource is defined in <<rc_tileSets-list>>.


^6^ The _DataSet_ origin is defined in Requirements Class "Dataset Tilesets" <<rc_datasetTileSets>> and depends on _OGC API - Common - Part 1: Core_.


^7^ The _Collection_ origin is defined in  Requirements Class "GeoData Tilesets" <<rc_geoDataResourceTileSets>> and depends on the _Collections_ requirements class defined in _OGC API - Common - Part 2: Geospatial data_


^8^ Styled tilesets rely on the ability to list styles defined in _OGC API - Styles_^2^.


^9^ Coverage tilesets rely on the _Coverage tiles_ conformance class defined in _OGC API - Coverages - Part 1: Core_^2^.


^10^ Map tilesets rely on the _Map tiles_ conformance class defined in _OGC API - Maps - Part 1: Core_^2^.
|===
