[[rc_tiles_core]]
== Requirement Class "Core"

[[core-overview]]

include::requirements/requirements_class_core.adoc[]

The core conformance class is designed as a very generic conformance class that describes a HTTP GET operation, as well as its response, to retrieve tiles from a tileset which can be described by the 2D Tile Matrix Set standard. It introduces the idea of URI templates and variables associated to the TileMatrix, TileRow and TileCol concepts defined in the 2D Tile Matrix Set standard but it does not prescribe a particular path or template form for the URL of those tiles.

With this conformance class alone, the way the tileset as a whole will be described is left open. Having a tileset description is important so the implementer of a Web API should define the tileset in conjunction with the core conformance class. This can be done by choosing  between conforming to the next conformance class (<<rc_tileSet>>) or using another mechanism such as TileJSON. (Currently TileJSON specification only supports WebMercatorQuad TileMatrixSet and the reference to it is implicit. TileJSON version 3 provides a additional mechanism to cite data sources).

=== Declaration of conformance classes
To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific Web API / server,
the Web API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of URIs to conformance classes.

include::requirements/core/REQ_conformance-success.adoc[]

If the Web API declares also conformity to OGC API - Common or to http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0],
then it has to consider the OGC API - Common requirements for declaring conformance, i.e. the use of a the conformance page.
In the JSON format the conformance page is an array of URIs following the schema defined in the OGC API - Common or in
http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0].
Below is an example fragment of a conformance information page of an Web API conformant to OGC API - Common and OGC API - Tiles.

[[ConformancePageCore]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core"
  ]
}
=================

Clients or servers are not required to support a specific default TileMatrixSet.

The OGC TileMatrixSets registry is available at http://opengis.net/def/tms.

=== A tile
A tile resource is a geospatial resource of a fragment of a more bigger geospatial data resource that is spatially constrained at the boundaries of the selected tile in a tile matrix set.

==== Operation
This operation allows retrieving a single tile that represents information coming from geospatial data resources.

include::requirements/core/REQ_tc-op.adoc[]

Typical geospatial data resources that can be retrieved as tiles are: vector features
(available at `/collections/{collectionId}/items` in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core],
for which it is recommended to provide tilesets at `/collections/{collectionId}/tiles`),
maps (specified in OGC - API Maps) or coverages (specified in OGC API - Coverages).

include::recommendations/core/REC_tc-op.adoc[]

The supported encodings, or more precisely the media types of the supported encodings, can be determined from the Web API definition. The desired encoding is selected using HTTP content negotiation.


The core of the OGC API - Tiles standard provides a mechanism to select and retrieve a tile in a TileMatrixSet.

==== Parameter tileMatrix
include::requirements/core/REQ_tc-tilematrix-definition.adoc[]

==== Parameter tileRow
include::requirements/core/REQ_tc-tilerow-definition.adoc[]

==== Parameter tileCol
include::requirements/core/REQ_tc-tilecol-definition.adoc[]

include::recommendations/core/PER_tc-tilematrixsetid-definition.adoc[]


==== Response

A successful response to a tile GET operation will be consistent with the media type of resource requested. This draft specification does not impose any media type or file format. For example:

* For features the media type may be GeoJSON or Mapbox Vector Tiles;
* For coverages the response may be a GeoTIFF;
* For maps the response may be a JPEG or a PNG.

include::requirements/core/REQ_tc-success.adoc[]

include::recommendations/core/PER_tc-core-tile-encoding.adoc[]

Normally, the content partially outside the tile bounding box will be clipped at the extent of the bounding box. This can be done efficiently when tiles are in raster format (e.g., map tiles). However, tiles containing features in vector format may not clip features that are partially outside to ensure continuity of features or for performance.

include::recommendations/core/REC_tc-success-scale.adoc[]

include::recommendations/core/REC_tc-deepfullempty.adoc[]

To enable search engines to easily discover the content offered by an implementation of OGC API - Tiles, as well as to enable web browsers to easily display the content offered by the Web APIs, this standard allows for responses to operations to be encoded in HTML.

include::recommendations/core/PER_tc-core-html.adoc[]

==== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

include::requirements/core/REQ_tc-error.adoc[]
