== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of [OGC 06-121r8], which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

For the purposes of this document, the following additional terms and definitions apply.

=== *geospatial resource*
A resource that consists in a set of geospatial data

=== *geospatial representation*
An resources that represents an aspect or data model (e.g. feature items, tiles, metadata, schemas,...) of a more generic geospatial resource (e.g. a collection)

NOTE: Do not confuse this with a resource representation. While resource representations share the same path and are selected by format negotiation, geospatial representations use different paths. Commonly a geospatial representations is a child path of a geospatial resource
