== Conventions
This section provides details of conventions used in this document.

=== Identifiers

The normative provisions in this standard are denoted by the URI `http://www.opengis.net/spec/ogcapi-tiles-1/1.0` .

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

=== Link relations

To express relationships between resources, http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#rfc8288[RFC 8288 (Web Linking)] is used.

The following http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#link-relations[registered link relation types] are used in this document.

* *alternate*: Refers to a substitute for this context.
* *item*: The target IRI points to a resource that is a member of the collection represented by the context IRI.
* *self*: Conveys an identifier for the link’s context.

In addition, the following link relation types are used for which no applicable registered link relation type could be identified.

* *conformance*: Refers to a resource that identifies the specifications that the link’s context conforms to.
* *tiles*: Refers to a resource that provides the description of the tiles represented by this geospatial resource

=== Use of HTTPS

For simplicity, this document in general only refers to the HTTP protocol. This is not meant to exclude the use of HTTPS and simply is a shorthand notation for "HTTP or HTTPS." In fact, most servers are expected to use http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#rfc2818[HTTPS], not http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#rc2616[HTTP].
