== Terms, definitions and abbreviated terms

////
Note that metanorma automatically adds the following text to this section. So, please keep the three paragraphs commented out to avoid repetition.

This document uses the terms defined in OGC Policy Directive 49, which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this document and OGC documents do not use the equivalent phrases in the ISO/IEC Directives, Part 2.

This document also uses terms defined in the OGC Standard for Modular specifications (OGC 08-131r3), also known as the ‘ModSpec’. The definitions of terms such as standard, specification, requirement, and conformance test are provided in the ModSpec.

For the purposes of this document, the following additional terms and definitions apply.
////

=== Terms and definitions

This document also uses terms defined in Sub-clause "Terms and Definitions" of OGC API - Common, Part 1: Core.

For the purposes of this document, the following additional terms and definitions apply.

==== coverage tile

_tile_ that contains information, often in a gridded form, where the values represent observations or measurements as a count, or quantity using some unit of measure

NOTE: Coverage tiles are generated in combination with _OGC API - Coverages_, and can also be generated by combining a subset (trim) and resampling operation. Usually, visualizing a coverage tile on a rendering device implies mapping those values to colors.

==== dataset
a set of data, published or curated by a single agent, and available for access or download in one or more representations (modified from DCAT: https://www.w3.org/TR/vocab-dcat-2/#dcat-scope).

NOTE: A Web API implementing OGC API - Common often gives access to a single dataset which may be comprised of one or more _geospatial data resources_.

==== geospatial data resource
web accessible resource that consists of a set of geospatial data

NOTE: In Web APIs implementing _OGC API - Common - Part 2: Geospatial Data_, geospatial data resources are referred to as collections and are defined in the _collections_ conformance class.

NOTE: _geodata_ is sometimes used in this document as an abbreviation of _geospatial data_

==== geospatial resource aspect
web accessible resource that represents a component of geospatial information (metadata, schemas...) or geospatial data accessed using a particular mechanism and data model (e.g., feature items, tiles, maps, coverages,...) of a more generic geospatial data resource (e.g., a collection)

NOTE: Not to be confused with a web accessible resource representation. While resource representations share the same path and are selected by format negotiation, geospatial aspects use different paths. Commonly a geospatial aspect is a subpath of a geospatial data resource.

==== map tile

_tile_ that contains information in a raster form where the values of cells are colors which can be readily displayed on rendering devices

NOTE: Map tiles are generated in combination with _OGC API - Maps_.

==== tile

geometric shape with known properties that may or may not be the result of a tiling (tessellation) process. A tile consists of a single connected "piece" without "holes" or "lines" (topological disc).

NOTE: From OGC 19-014r1: Core Tiling Conceptual and Logical Models for 2D Euclidean Space

In the context of a 2D _tile matrix_, a _tile_ is one of the rectangular regions of space, which can be uniquely identified by row and column integer indices, making up the tile matrix.

In the context of a geospatial data _tile set_, a _tile_ contains data for such a partition of space as part of an overall set of tiles for that tiled geospatial data.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set and Tile Set Metadata standard

NOTE: Tiles are useful to efficiently request, transfer, cache, display, store and process geospatial data for a specific resolution and area of interest, providing deterministic performance and scalability
for arbitrarily large datasets.

NOTE: Tiles can contain a variety of data types, such as grid-based pictorial representations (map tiles), coverage subsets (coverage tiles), or feature-based representations (vector tiles).

==== tile matrix

tiling grid in a given 2D coordinate reference system, associated to a specific scale and partitioning space into regular conterminous _tiles_, each of which being assigned a unique identifier

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set and Tile Set Metadata standard

NOTE: Each tile of a tile matrix is uniquely identifiable by a row and a column integer index. The number of rows is referred to as the _matrix height_, while the maximum number of columns is referred to
as the _matrix width_ (the number of columns can vary for different rows in _variable width tile matrices_).

==== tile matrix set

_tiling scheme_ consisting of a set of _tile matrices_ defined at different scales covering approximately the same area and having a common coordinate reference system.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set and Tile Set Metadata standard

==== tile indexing scheme
scheme to uniquely reference a _tile_ in a _tiling scheme_ by the use of a unique identifier (or set of identifiers), and reversely, which unique identifier (or unique set of identifiers) corresponds
to a space satisfying the geometric properties of a specific tile

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set and Tile Set Metadata standard

==== tile set

a set of _tiles_ resulting from tiling data according to a particular _tiling scheme_

NOTE: From OGC 19-014r1: Core Tiling Conceptual and Logical Models for 2D Euclidean Space, but adapted to clarify that in the context of this document, a tile set refers specifically to a set of tiles containing
data and following a common tiling scheme.

==== tiling scheme

scheme that defines how space is partitioned into individual _tiles_, potentially featuring multiple levels of detail (each tiling at a different granularity to reflect a different resolution or scale)

A tiling scheme defines the spatial reference system and the geometric properties of each tile defined by the scheme.
Those properties include which space each tile occupies, such as the tiles spatial extent, as well as a tile coordinate origin if a particular corner of origin convention is established.

NOTE: A tiling scheme can be defined on top of a CRS as well as other spatial reference systems such as DGGS and other organizations including irregular ones.
In this document, only tiling schemes based on CRSs are supported.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set and Tile Set Metadata standard

==== tile set metadata

additional metadata beyond the common properties defining the _tile set_. Such metadata could be an abstract, the owner, the author, or other common metadata. [OGC 19-014r3]

metadata describing common properties defining a _tile set_, layers and styles used to produce the tile set, the limits of the tile matrix with actual data and common metadata such as abstract, owner, author, etc.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set and Tile Set Metadata standard

==== vector tile (aka tiled vector or feature data)

tile that contains vector data that has been generalized (simplified) at the tile scale resolution and clipped by the tile boundaries.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set and Tile Set Metadata standard

==== Web API

API using an architectural style that is founded on the technologies of the Web [source: OGC API - Features - Part 1: Core]

NOTE: See link:https://www.w3.org/TR/dwbp/#APIHttpVerbs[Best Practice 24: Use Web Standards as the foundation of APIs] (W3C Data on the Web Best Practices) for more detail.
