== Requirement Class "Tiles core"

=== Overview

[[tiles-core-overview]]

include::requirements/tiles/requirements_class_core.adoc[]

This is a building block for the an OGC API that is able to provide geospatial resources. When applying the building block to a geospatial resource, it becomes available as tiles. The server can select which resources are available as tiles and will advertise which resources are available as tiles.

This building block does not specify how to get an API definition, the conformance class list or the geospatial resources lists. The standard assumes that the first two are defined by an API specification (e.g. OGC API Common) and the later by an OGC API for geospatial resource (e.g. OGC API Features).

The core of the OGC API - Tiles core draft specification does not mandate the inclusion of an explicit definition of any TileMatrixSet. This draft specification assumes that clients and services know about the eight TileMatrixSets defined in OGC 17-083r2 annex D (or compatible future update of it) and there is no need to define new TileMatrixSets. An extension to the core provides the capability to include definitions of flexible TileMatrixSets that are explicitly defined.

This draft specification assumes that data is organized in on or more geospatial resources (e.g. the "collections" in OGC API features). Geospatial resources are referenced using URIs.

This document does not specify any requirements for geospatial resources, and they could be  features, coverages, a resource that does not represent data per-se (e.g. an annotation) as far as they can be represented a tile. The resource path replaces the concept of layer in WMS and WMTS. In this core tiles can be generated from only one geospatial resource (tiles that are generated as a combination of geospatial resources will be defined as an extension).

Accessing the geospatial resource content (other than as tiles) or its descriptions is out of the scope of this draft specification. If a description of the geospatial resource exists and it has a mechanism to add links to it, this specification will indicate the need to add a link to the tile representation description.

The tile representation description will include metadata about tiles as well as links to other resources including at least one with a template to get individual tiles.

=== General
include::requirements/tiles/core/REQ_api-common.adoc[]

In practice, this means that the landing page and the conformance page follow OGC API - Common core and collections requirement classes. This draft specification provides extra additions to the OGC API - Common requirements that are particular to tiles.

=== API landing page

The landing page provides links to start exploring the resources offered by the API. The landing page mainly consists of a list of links. OGC API - Common already requires some common links that are enough for this draft specification core.

==== Response
There are no required variations to the landing page.

=== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of links. OGC API - Common already requires some links.

include::requirements/tiles/core/REQ_conformance-success.adoc[]

In the conformance page (typically in JSON format) the links follow the link schema defined in the OGC API - Common. Below is an example fragment of the response to an OGC API - Tiles conformance information page.

[[ConformancePageTilesCore]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/req/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/req/core"
  ]
}
=================

=== Collections
This draft specification includes dependencies on OGC API - Common collections. Collections are mandatory in the core of this draft specification because collections are the object that will be included in a tile.

Collections will enumerate the collectionId identifiers available in this implementation of the OGC API draft specification as well as basic information about each collectionId: id, title, description, extent, CRS and links. This common response is considered enough for a general description of the collection.

include::requirements/tiles/core/REQ_tc-md-collection-links.adoc[]

More specific details about the collection can be found following the link to the individual collections that follow the pattern /collections/{collectionId}

NOTE: The collectionId substitutes the concept of "layer" in WMTS 1.0.

=== Collection
This draft specification includes dependencies on the OGC API - Common collection requirement. The response to the operation is extended with a new link for the tiles description.

==== Collection Links

include::requirements/tiles/core/REQ_tc-tile-desc-links.adoc[]

.Fragment of the collection links.
=================
[source,JSON]

  "id": "buildings",
  "title": "Buildings in the city of Bonn",
  "description": "This collection contains buildings",
  "attribution": "OpenStreetMap",
  "extent": {
    ...
  }
  "links": [
    ...
    {
      "href": "http://data.example.com/collections/buildings/tiles",
      "rel": "tiles",
      "type": "application/json",
    }
  ]
}
=================

=== Tiles description
The response to this operation contains the necessary metadata to enable a client application to formulate a tile request from a single collection.

==== Operation

include::requirements/tiles/core/REQ_sct-op.adoc[]

The request of this operation has no parameters.

==== Response

A successful response to a tiles request for a collection that can be retrieved as tiles will respond with a data structure with specific information necessary to get tiles representing the resource collection. In this core draft specification, the response is only required to inform about from which tile matrix sets tiles can be retrieved and the URL template to a tile.

include::requirements/tiles/core/REQ_sct-tmxslink.adoc[]

[[TilesLinkResponseExample]]
.Example of a tiles metadata response.
=================
[source,JSON]
{
  "tileMatrixSetLinks": [
    {
      "tileMatrixSet": "WorldMercatorWGS84Quad",
      "tileMatrixSetURI": "http://schemas.opengis.net/tms/1.0/json/examples/WorldMercatorWGS84Quad.json"
    }
  ],
  ...
  "links": [
    ...
    {
     "href": "http://data.example.com/collections/buildings/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}.png",
     "rel": "item",
     "type": "image/png",
   }
   ...
  ]
}
=================

include::recommendations/tiles/core/REC_sct-tmxslink.adoc[]

Resolvable URLs for the 8 URIs defined in the OGC 17-083r2 Annex D are available in the OGC schemas repository in XML, JSON and RDF formats. For example, JSON descriptions can be found here: http://schemas.opengis.net/tms/1.0/json/examples/

include::requirements/tiles/core/REQ_sct-tile-examples.adoc[]

One common order used in URL templates for tiles is .../tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}, but this draft specification allows for other URL template composition.

[#URL_template_tile_core,reftext='{table-caption} {counter:table-num}']
.URI template variables for tiles and valid values
[cols="30,35,70",options="header"]
!===
|URL template variable |Meaning |Possible values
|TileMatrixSetId |tile matrix set identifier |One of the identifiers included in Annex D of OGC 17-083r2 or an identifier defined by extensions of this core
|TileMatrix |tile matrix identifier |Identifier of the tile matrix (representing a zoom level, a.k.a. a scale) listed in the TileMatrixSet definition
|TileRow |row index of tile matrix	|A non-negative integer between 0 and the MatrixHeight – 1. If there is a TileMatrixSetLimits the value is limited between MinTileRow and MaxTileRow
|TileCol |column index of tile matrix	|A non-negative integer between 0 and the MatrixWidth – 1. If there is a TileMatrixSetLimits the value is limited between MinTileCol and MaxTileCol
!===

.link to get tiles as a URL template in the tiles metadata response fragment
=================
[source,JSON]
links:
[
    {
      "href": "http://data.example.com/collections/buildings/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}",
      "rel": "tiles",
      "type": "image/png",
    }
]
=================

=== Tiled data from one collection

The core of the OGC API -Tiles draft specification provides a mechanism to select and retrieve a tile in a TileMatrixSet. If the service does not advertise any other TileMatrixSet (this core does not describe any mechanism to do that, but an extension will do it) only the TileMatrixSet identifiers specified in the Annex D.1 of the OGC 17-083r2 standard can be used.

==== Operation

include::requirements/tiles/core/REQ_tc-op.adoc[]

Typical resources that can be retrieved as tiles are: features (/collections/{collectionId}), coverages (/collections/{collectionId}/coverage/{coverageId} or /coverage/{coverageId}) or maps (/collections/{collectionId}/map/styleId}).

NOTE: The common path for coverages is still under discussion.

==== Parameter tileMatrixSetId
include::requirements/tiles/core/REQ_tc-tilematrixsetid-definition.adoc[]

==== Parameter tileMatrix
include::requirements/tiles/core/REQ_tc-tilematrix-definition.adoc[]

==== Parameter tileRow
include::requirements/tiles/core/REQ_tc-tilerow-definition.adoc[]

==== Parameter tileCol
include::requirements/tiles/core/REQ_tc-tilecol-definition.adoc[]

==== Response

A successful response to a tile request will be consistent with the media type of resource requested. This draft specification does not impose any media type. For example:

* For features the media type can be geojson or Mapbox vector tiles;
* For coverages the response may be a geotiff;
* For maps the response may be a jpeg or a png.

include::requirements/tiles/core/REQ_tc-success.adoc[]

Normally, the content partially outside the tile bounding box will be clipped and this is particularly true when tiles are in raster format. Nevertheless, tiles containing features in vector format may not clip features that are partially outside.

include::recommendations/tiles/core/REC_tc-success-scale.adoc[]

==== Error conditions

A general summary of the HTTP status codes can be found in the OGC API - Common.

If the parameter value `tileMatrixSetId` is not available by the server for this resource or the parameters values `tileMatrix`, `tileRow`, `tileCol` are out-of-range, the status code of the response will be 404.
