[[rc_tileSets-list]]
== Requirement Class "TileSets List"

=== Overview

[[tiles-core-overview]]

include::requirements/requirements_class_tilesets-list.adoc[]

This class defines a resource called _tilesets list_ that provides a list of available tilesets for a resource. It also defines a how to link to individual tileset resources, which are defined in the <<rc_tileSet>>.
Refer to the <<rc_datasetTileSets>> and <<rc_geoDataResourceTileSets>> classes that describes two complementary mechanisms to associate tilesets to datasets and to geospatial data resources, respectively.

=== Tilesets list
A _tilesets list_ resource represents a list of sets of tiles, each one belonging to a particular TileMatrixSet.
Each _tileset_ resource returns the necessary metadata to enable a client application to formulate a tile request.

==== Tilesets path
This class does not specify the full path to a tileset list but requires that it ends with `/tiles`.

include::requirements/tilesets-list/REQ_tilesets-list_tileset-path.adoc[]

==== Response

A successful GET response to a list of tilesets resource will respond with a data structure that lists the tileset URLs available (one for each Tile Matrix Set supported).

include::requirements/tilesets-list/REQ_tilesets-list_tileset-links.adoc[]


[[TilesetsTilesLinkResponseExample]]
.Example of a tilesets list response
=================
[source,JSON]
{
  "tilesets": [
    ...
    {
      "title" : "Buildings (WebMercatorQuad)",
      "tileMatrixSetURI" : "http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad",
      "crs" : "http://www.opengis.net/def/crs/EPSG/0/3857",
      "dataType" : "vector",
      "links" : [
         {
           "rel": "self",
           "href": "http://data.example.com/collections/buildings/tiles/WebMercatorQuad",
           "type": "application/json"
         },
         {
           "rel": "http://www.opengis.net/def/rel/ogc/1.0/tiling-scheme",
           "href": "http://data.example.com/tileMatrixSets/WebMercatorQuad",
           "type": "application/json"
         }
      ]
   }
   ...
  ]
}
=================

include::recommendations/tilesets-list/REC_tilesets-list_title.adoc[]

include::recommendations/tilesets-list/PER_tilesets-list_api.adoc[]
