[[rc_tileSet]]
== Requirements Class "TileSet"

=== Overview

[[tile-set-overview]]

include::requirements/requirements_class_tileset.adoc[]

The _tileset_ Requirements Class provides a mechanism to retrieve metadata for a set of tiles of geospatial data tiled according to one specific TileMatrixSet.
This Class also provides a mechanism to obtain a templated link to retrieve individual tiles as defined in the _core_ conformance class.

This Class describes the HTTP GET operation for accessing a tileset resource and its response but does not prescribe a specific path.
The response provides metadata as per the https://docs.ogc.org/is/17-083r4/17-083r4.html[OGC Two Dimensional Tile Matrix Set and Tile Set Metadata 2.0] Standard.

The essential elements of this metadata are:

- A link to the definition of the TileMatrixSet (either one registered in the https://defs.opengis.net/vocprez/object?uri=http%3A//www.opengis.net/def/tms[OGC TileMatrixSet register] that is controlled by the https://www.ogc.org/standards/na[OGC Naming Authority (OGC-NA)] SubCommittee (SC), or to a custom TileMatrixSet definition).
- A TileMatrixSet URI in the case of a TileMatrixSet registered with an authority (e.g. the OGC TileMatrixSet register).
- A Coordinate Reference System (usually provided as a URI).
- A templated link (URI) to individual tiles.
- A data type (indicating whether the tileset consists of vector, coverage or map tiles).

Metadata may optionally also provide additional information, such as:

- A title.
- A description.
- The limits of the tileset if it does not span the full extent of the TileMatrixSet.
- The geospatial data resources involved in the creation of the tiles (potentially including links to OGC API collections).
- A schema of the available properties contained within the tiles.
- Styles used to create the tiles.
- A central point on which a viewer may initially focus.
- Attribution.

A link to a definition of a TileMatrixSet is always required whether a custom TileMatrixSet or a registered TileMatrixSet is used.
Having the Web API hosts a local definition of each supported TileMatrixSet to ensure availability is recommended.   

=== Tileset resource
A tileset consists of a set of tiles obtained by partitioning geospatial data according to a particular TileMatrixSet.
The tileset metadata contains all the information necessary for a client application to request tiles from the tileset.

==== Tileset path

This class does not specify a full path to a tileset. Generally, _tileset_ resources are linked from a _tilesets list_ resource
(refer to the Requirements Class "Tilesets List" (<<rc_tileSets-list>>) for how to list available tilesets and link to individual tileset resources).
Refer to the Requirements Class "Dataset Tilesets" (<<rc_datasetTileSets>>) and Requirements Class "GeoData Tilesets" (<<rc_geoDataResourceTileSets>>) for a description of two mechanisms that associate lists of tilesets to
an OGC API landing page for a dataset and to geospatial data (collection) resources respectively.
The expectation is that a tileset can be used as a building block in other Web APIs and can be used to provide tiles of different types of data such as maps, features, coverages, or other types of geospatial data that can benefit from tiling.

==== Response
A successful GET response to a tileset resource is metadata consisting of a data structure with the specific information necessary to build a complete GET request of the tiles representing the geospatial data resource.

include::requirements/tileset/REQ_tileset-description.adoc[]


In addition to the recommendation to include links in the HTTP response headers as specified in OGC API - Common - Part 1,
this Standard recommends following the https://www.ietf.org/archive/id/draft-ietf-httpapi-link-template-00.html[Link-Template HTTP Header Field] draft specification,
to include `Link-Template` for templated links, such as the URI for individual tiles.

include::recommendations/tileset/REC_header_linktemplates.adoc[]


See <<rc_xml>> for providing an XML representation of the tileset metadata.

Support for alternative encodings for tileset metadata can be added, such as https://github.com/mapbox/tilejson-spec[TileJSON].

Currently, use of the TileJSON specification usually implies a WebMercatorQuad TileMatrixSet and the reference to it is implicit. TileJSON version 3 provides an additional mechanism to cite data sources.

include::recommendations/tileset/REC_tmxslink.adoc[]

include::recommendations/tileset/REC_tileset_bbox.adoc[]

include::recommendations/tileset/REC_conf_link.adoc[]

Clients or servers are not required to support a specific default TileMatrixSet.

NOTE: The OGC TileMatrixSets register is based on the OGC Two Dimensional Tile Matrix Set and Tile Set Metadata standard, version 2.0 (OGC 17-083r4). Refer to Annex D and E for commonly used TileMatrixSets.



NOTE: When this Requirements Class is used together with the GeoData Tilesets Requirements Class, the geospatial data resource URL is typically the first part of the URL template, but this standard does not mandate this (e.g., the tileset metadata and tiles could be hosted on more affordable object storage).

[[TilesetTilesURIResponseExample]]
.Example fragment of a tileset response for a common TileMatrixSet defined in the OGC TileMatrixSet register
=================
[source,JSON]
{
  ...
  "tileMatrixSetURI": "http://www.opengis.net/def/tilematrixset/OGC/1.0/WorldMercatorWGS84Quad",
  "dataType": "map",
  "crs": "http://www.opengis.net/def/crs/EPSG/0/3395",
  "links": [
    ...
    {
     "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad",
     "rel": "self",
     "type": "application/json",
     "title": "Buildings tileset tiled using World Mercator TileMatrixSet"
    },
    {
     "href": "http://schemas.opengis.net/tms/2.0/json/examples/WorldMercatorWGS84Quad.json",
     "rel": "http://www.opengis.net/def/rel/ogc/1.0/tiling-scheme",
     "type": "application/json",
     "title": "Definition of WorldMercatorQuad TileMatrixSet"
    },
    {
     "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad/{tileMatrix}/{tileRow}/{tileCol}.png",
     "templated": true,
     "rel": "item",
     "type": "image/png",
     "title": "Templated link for retrieving PNG tiles"
    }
   ...
  ],
  "tileMatrixSetLimits":
  [
    { "tileMatrix" : "0", "minTileRow" : 0, "maxTileRow" : 0, "minTileCol" : 0, "maxTileCol" : 0 },
    { "tileMatrix" : "1", "minTileRow" : 0, "maxTileRow" : 0, "minTileCol" : 1, "maxTileCol" : 1 },
    { "tileMatrix" : "2", "minTileRow" : 1, "maxTileRow" : 1, "minTileCol" : 2, "maxTileCol" : 2 },
    { "tileMatrix" : "3", "minTileRow" : 3, "maxTileRow" : 3, "minTileCol" : 4, "maxTileCol" : 4 },
    ...
  ]
}
=================

NOTE: The use of "templated" is inspired by the JSON Hypertext Application Language (HAL), https://tools.ietf.org/html/draft-kelly-json-hal-08.

The following table explains the meaning of the URI template variables.

[#URL_template_tile_core,reftext='{table-caption} {counter:table-num}']
.URI template variables for tiles and valid values
[cols="30,35,70",options="header"]
!===
|URL template variable |Meaning |Possible values
|TileMatrix |tile matrix identifier |Identifier of the tile matrix (representing a zoom level, a.k.a. a scale) listed in the TileMatrixSet definition
|TileRow |row index of tile matrix	|A non-negative integer between 0 and the MatrixHeight - 1. If there is a TileMatrixSetLimits the value is limited between MinTileRow and MaxTileRow
|TileCol |column index of tile matrix	|A non-negative integer between 0 and the MatrixWidth - 1. If there is a TileMatrixSetLimits the value is limited between MinTileCol and MaxTileCol
!===

[[TilesetTilesLinkResponseExample]]
.Example fragment of a tileset response for a Web API-defined TileMatrixSet
=================
[source,JSON]
{
  ...
  "dataType": "map",
  "crs": "http://www.opengis.net/def/crs/EPSG/0/2001",
  "links": [
    ...
    {
     "href": "http://data.example.com/collections/buildings/tiles/CustomAntiguaTMS",
     "rel": "self",
     "type": "application/json",
     "title": "Buildings tileset tiled using custom Antigua TileMatrixSet"
    },
    {
     "href": "http://data.example.com/collections/buildings/tiles/CustomAntiguaTMS/{tileMatrix}/{tileRow}/{tileCol}.png",
     "templated": true,
     "rel": "item",
     "type": "image/png",
     "title": "Templated link for retrieving PNG tiles"
    },
    {
     "href": "http://data.example.com/tileMatrixSets/CustomAntiguaTMS",
     "rel": "http://www.opengis.net/def/rel/ogc/1.0/tiling-scheme",
     "type": "application/json",
     "title": "Definition of custom Antigua TileMatrixSet"
    }
   ...
  ],
  "tileMatrixSetLimits":
  [
    ...
  ]
}
=================

=== Web API-defined TileMatrixSets

This section provides more details on the recommendations for implementing TileMatrixSets in Web API based servers and client applications. In the future, an extension of this Standard may describe a mechanism to manage (create, update, …) tiling schemes for a Web application implementing OGC API definitions including OGC API – Tiles Requirements Classes and make some of the recommendations mandatory.

==== Web API Landing Page

An OGC API landing page provides links to start exploring the resources offered by the Web API. A landing page mainly consists of a list of links. New links for TileMatrixSets on top of the ones defined in _OGC API - Common_ are introduced.

Using the JSON format, the landing page links follow the link schema defined in _OGC API - Common_. The following is an example fragment of the response to an OGC API - Tiles landing page.

[[landingPageTilesTmxs]]
.Web API Landing Page fragment with links to TileMatrixSet descriptions.
=================
[source,JSON]
----
{
  "links": [
    ...
    {
      "href": "http://data.example.org/tileMatrixSets?f=json",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/tiling-schemes",
      "type": "application/json",
      "title": "List of tileMatrixSets implemented by this API in JSON"
    },
    {
      "href": "http://data.example.org/tileMatrixSets?f=html",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/tiling-schemes",
      "type": "text/html",
      "title": "List of tileMatrixSets implemented by this API in HTML"
    }
  ]
}
----
=================

==== TileMatrixSets

An HTTP request to the TileMatrixSets endpoint retrieves a list of links to the descriptions of the tile matrix sets supported by the OGC Web API. The MAY be the TileMatrixSets defined in the Annex D and the Annex E of the https://docs.ogc.org/is/17-083r4/17-083r4.html[OGC Two Dimensional Tile Matrix Set and Tile Set Metadata 2.0] Standard or customized ones. The response follows the schema below.

[[TileMatrixSetsResponseSchema]]
.Schema for the TileMatrixSets resource
=================
[source,YAML]
  type: object
  required:
    - tileMatrixSets
  properties:
    tileMatrixSets:
      type: array
      items:
        $ref: '#/components/schemas/id-link'
=================

[[TileMatrixSetsResponseCommonSchema]]
.Schema for id-link from OGC API - Common used in TileMatrixSets resource.
=================
[source,YAML]
id-link:
  type: object
  description: |-
    Reusable object that contains an id to a resource and links where the object is described or a representation retrieved. Typically it is useful for paths like `/resources` and `/resources/{resourceId}`.   `/resources` will respond an array of id-link listing the `resourceId` and the links to get it. /collections and /collections/{collectionId} is an exception to this pattern.
    The fact that `links` is an array can be used to advertise the same object representation in different formats.
  required:
    - id
    - links
  properties:
    id:
      type: string
    tileMatrixSetURI:
      type: string
      format: uri
      description: If the Tile Matrix Set is registered in the Definitions Server, this property should the reference to this definition
    title:
      type: string
    links:
      type: array
      minItems: 1
      items:
        $ref: '#/components/schemas/link'
=================

[[TileMatrixSetsResponseExample]]
.Example for the TileMatrixSets resource
=================
[source,JSON]
{
  "tileMatrixSets": [
    {
      "id": "MyWebMercatorQuad",
      "uri": "http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad"
      "title": "My Google Maps Compatible for the World",
      "links": [
        {
          "rel": "self",
          "href": "https://data.example.org/tileMatrixSets/MyWebMercatorQuad",
          "type": "application/json",
          "title": "Local definition of WebMercatorQuad TileMatrixSet"
        }
      ]
    }
  ]
}
=================

==== TileMatrixSet

A HTTP GET request to a TileMatrixSet endpoint retrieves the full description of a tile matrix set supported by Web API based servers and client applications following the schema described in the https://docs.ogc.org/is/17-083r4/17-083r4.html[OGC Two Dimensional Tile Matrix Set and Tile Set Metadata 2.0] Standard. The response follows the TileMatrixSet schema.

[[TileMatrixSetResponseExample]]
.Fragment of a TileMatrixSet resource example
=================
[source,JSON]
{
  "title": "My TileMatrixSet for the World",
  "id": "MyTMS",
  "uri": "http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad",
  "crs": "http://www.opengis.net/def/crs/EPSG/0/3857",
  "wellKnownScaleSet": "http://www.opengis.net/def/wkss/OGC/1.0/GoogleMapsCompatible",
  "tileMatrices": [
    ...
    {
      "title": "My zoom level 3",
      "id": "3",
      "scaleDenominator": 69885283.0035897,
      "cellSize": 19567.8792410051,
      "pointOfOrigin": [-20037508.3427892,20037508.3427892],
      "tileWidth": 256,
      "tileHeight": 256,
      "matrixWidth": 8,
      "matrixHeight": 8
    }
    ...
  ]
}
=================
