[[rc_tileSet]]
== Requirement Class "TileSet"

=== Overview

[[tile-set-overview]]

include::requirements/requirements_class_tileset.adoc[]

The tileset conformance class provides a mechanism to retrieve the description of a single tileset, for one particular geospatial data resource and tiled according to one specific TileMatrixSet.
It also provides a mechanism to obtain a templated link to retrieve individual tiles as defined in the _core_ conformance class.

It describes the HTTP GET operation on a tileset resource and its response, but does not prescribe an specific path.
The response provides metadata as per the 2D Tile Matrix Set and TileSet Metadata standard.

The essential elements of this metadata are:
- a link to the definition of the TileMatrixSet (either one registered in the OGC TileMatrixSet registry, or to a custom TileMatrixSet definition),
- a templated link (URI) to individual tiles,
- and a data type (indicating whether the tileset consists of vector, coverage or map tiles).

It may optionally also provide additional information, such as:
- the geospatial data resources involved in the creation of the tiles (potentially including links to OGC API collections),
- a schema of the available properties contained within the tiles,
- styles used to create the tiles,
- a central point on which a viewer may initially focus,
- attribution.

The explicit definition of a TileMatrixSet is only required for custom TileMatrixSet not registered in the OGC TileMatrixSet registry.
However, it is recommended that the Web API always provides a link to a local definition of the TileMatrixSets used.

Services and clients are encouraged to support as many of the TileMatrixSets defined in the OGC TileMatrixSet registry as possible to maximize
interoperability, but support is not required for any specific tile matrix set.
See also annexes D and H for TileMatrixSets defined and registered at the time of publication of this specification.

=== Declaration of conformance classes
To support "generic" clients wishing to access multiple OGC API standards and extensions - and not "just" a specific Web API / server,
the Web API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of links.

include::requirements/tileset/REQ_conformance-success.adoc[]

If the server declares also conformity to OGC API - Common or to http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0], then it has to consider the OGC API - Common requirements for declaring conformance, i.e. the use of a the conformance page. In the JSON format the conformance page is an array of links following the link schema defined in the OGC API - Common or in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0]. Below is an example fragment of a conformance information page of an Web API conformant to OGC API - Common and OGC API - Tiles.

[[ConformancePageTileset]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset"
  ]
}
=================

=== Tileset resource
A tileset consists of a set of tiles obtained by partitioning geospatial data according to a particular TileMatrixSet.
The tileset description resource contains all the information necessary for a client application to request tiles from that tileset.

==== Tileset path

This class does not specify a full path to a tileSet. Generally, TileSet resources are linked from a Tilesetslist resource (see <<rc_tileSets-list>>).
Refer to the _tilesets list_ conformance class to know how to list available TileSets and link to individual TileSet resources.
Refer to the _dataset tilesets_ and _geodata tilesets_ conformance classes describing two mechanisms to associate list of tilesets to
OGC API dataset (landing page) and to geospatial data (collection) resources respectively.
It is expected that a tileset can be used as a building block in other Web APIs and on top of resources such as maps, features, coverages or any other geospatial resources that can benefit from tiling.

==== Response
A successful GET response to a tileset resource will be a data structure with the specific information necessary to build a complete GET request to the tiles representing the geospatial data resource.

include::requirements/tileset/REQ_tileset-description.adoc[]

Alternative encodings for tileset metadata can be supported, such as TileJSON.

include::recommendations/tileset/REC_tmxslink.adoc[]

Clients or servers are not required to support a specific default TileMatrixSet.

NOTE: The OGC TileMatrixSets registry is based on the OGC Two Dimensional Tile Matrix Set standard.

//include::requirements/tileset/REQ_tile-template.adoc[]

NOTE: The geospatial data resource URL is expected to be the first part of the URL template (presented by the '...' in the previous note) but this standard does not mandate this.

[[TilesetTilesURIResponseExample]]
.Example fragment of a tileset response for a common TileMatrixSet defined in the OGC NA
=================
[source,JSON]
{
  ...
  "tileMatrixSetURI": "http://www.opengis.net/def/tilematrixset/OGC/1.0/WorldMercatorWGS84Quad",
  "dataType": "map",
  "links": [
    ...
    {
     "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad",
     "rel": "self",
     "type": "application/json",
    },
    {
     "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad/{tileMatrix}/{tileRow}/{tileCol}.png",
     "templated": true,
     "rel": "item",
     "type": "image/png",
    }
   ...
  ],
  "tileMatrixSetLimits":
  [
    { "tileMatrix" : "0", "minTileRow" : 0, "maxTileRow" : 0, "minTileCol" : 0, "maxTileCol" : 0 },
    { "tileMatrix" : "1", "minTileRow" : 0, "maxTileRow" : 0, "minTileCol" : 1, "maxTileCol" : 1 },
    { "tileMatrix" : "2", "minTileRow" : 1, "maxTileRow" : 1, "minTileCol" : 2, "maxTileCol" : 2 },
    { "tileMatrix" : "3", "minTileRow" : 3, "maxTileRow" : 3, "minTileCol" : 4, "maxTileCol" : 4 },
    ...
  ]
}
=================

NOTE: The use of "templated" is inspired by the JSON Hypertext Application Language (HAL), https://tools.ietf.org/html/draft-kelly-json-hal-08

The following table explains the meaning of the URI template variables.

[#URL_template_tile_core,reftext='{table-caption} {counter:table-num}']
.URI template variables for tiles and valid values
[cols="30,35,70",options="header"]
!===
|URL template variable |Meaning |Possible values
|TileMatrix |tile matrix identifier |Identifier of the tile matrix (representing a zoom level, a.k.a. a scale) listed in the TileMatrixSet definition
|TileRow |row index of tile matrix	|A non-negative integer between 0 and the MatrixHeight - 1. If there is a TileMatrixSetLimits the value is limited between MinTileRow and MaxTileRow
|TileCol |column index of tile matrix	|A non-negative integer between 0 and the MatrixWidth - 1. If there is a TileMatrixSetLimits the value is limited between MinTileCol and MaxTileCol
!===

[[TilesetTilesLinkResponseExample]]
.Example fragment of a tileset response for a Web API defined TileMatrixSet
=================
[source,JSON]
{
  ...
  "dataType": "map",
  "links": [
    ...
    {
     "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad",
     "rel": "self",
     "type": "application/json",
    },
    {
     "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad/{tileMatrix}/{tileRow}/{tileCol}.png",
     "templated": true,
     "rel": "item",
     "type": "image/png",
    },
    {
     "href": "http://data.example.com/TileMatrixSets/MyTilingScheme",
     "rel": "http://www.opengis.net/def/rel/ogc/1.0/tiling-schemes",
     "type": "application/json",
    }
   ...
  ],
  "tileMatrixSetLimits":
  [
    ...
  ]
}
=================

===== Web API defined TileMatrixSets

This section provides more details on the recommendations for Web API defined TileMatrixSets. In the future, an extension of this standard could described mechanism to manage (create, update...) tiling schemes for an Web API and make some of the recommendations expressed in the section mandatory.

====== Web API landing page

The landing page provides links to start exploring the resources offered by the Web API. It mainly consists in a list of links. New links for TileMatrixSets on top of the common ones are introduced.

In the landing page, in JSON format, the links follow the link schema defined in the OGC API - Common. The following is an example fragment of the response to an OGC API - Tiles landing page.

[[landingPageTilesTmxs]]
.Web API Landing Page fragment with links to TileMatrixSet descriptions
=================
[source,JSON]
----
{
  "links": [
    ...
    {
      "href": "http://data.example.org/tileMatrixSet?f=json",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/tiling-schemes",
      "type": "application/json",
      "title": "List of tileMatrixSets implemented by this API in JSON",
    },
    {
      "href": "http://data.example.org/tileMatrixSet?f=html",
      "rel": "http://www.opengis.net/def/rel/ogc/1.0/tiling-schemes",
      "type": "text/html",
      "title": "List of tileMatrixSets implemented by this API in HTML",
    }
  ]
}
----
=================

====== TileMatrixSets

The TileMatrixSets endpoint retrieves links to the descriptions of the tile matrix sets supported by the Web API in addition to the TileMatrixSets defined in the Annex D and the Annex G of the OGC 17-083r2 standard. The response follows the schema below.

[[TileMatrixSetsResponseSchema]]
.Schema for the TileMatrixSets resource
=================
[source,YAML]
  type: object
  required:
    - tileMatrixSets
  properties:
    tileMatrixSets:
      type: array
      items:
        $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/schemas/id-link'
=================

[[TileMatrixSetsResponseCommonSchema]]
.Schema for id-link from OGC API - Common used in TileMatrixSets resource.
=================
[source,YAML]
id-link:
  type: object
  description: |-
    Reusable object that contains an id to a resource and links where the object is described or a representation retrieved. Typically it is useful for paths like `/resources` and `/resources/{resourceId}`.   `/resources` will respond an array of id-link listing the `resourceId` and the links to get it. /collections and /collections/{collectionId} is an exception to this pattern.
    The fact that `links` is an array can be used to advertise the same object representation in different formats.
  required:
    - id
    - links
  properties:
    id:
      type: string
    tileMatrixSetURI:
      type: string
      format: uri
      description: If the Tile Matrix Set is registered in the Definitions Server, this property should the reference to this definition
    title:
      type: string
    links:
      type: array
      minItems: 1
      items:
        $ref: '#/components/schemas/link'
=================

[[TileMatrixSetsResponseExample]]
.Example for the TileMatrixSets resource
=================
[source,JSON]
{
  "tileMatrixSets": [
    {
      "id": "MyWebMercatorQuad",
      "title": "My Google Maps Compatible for the World",
      "links": [
        {
          "href": "https://data.example.org/tileMatrixSet/MyWebMercatorQuad",
          "rel": "item",
          "type": "application/json"
        }
      ]
    }
  ]
}
=================

====== TileMatrixSet

The TileMatrixSet endpoint retrieves the full description of a tile matrix set supported by the Web API following the schema described in the OGC 17-083r2 standard. The response follows the TileMatrixSet schema.

[[TileMatrixSetResponseExample]]
.Fragment of a TileMatrixSet resource example
=================
[source,JSON]
{
  "title": "My TileMatrixSet for the World",
  "identifier": "MyTMS",
  "supportedCRS": "http://www.opengis.net/def/crs/EPSG/0/3857",
  "wellKnownScaleSet": "http://www.opengis.net/def/wkss/OGC/1.0/GoogleMapsCompatible",
  "tileMatrices": [
    ...
    {
      "title": "My zoom level 3",
      "id": "3",
      "scaleDenominator": 69885283.0035897,
      "cellSize": 19567.8792410051,
      "pointOfOrigin": [-20037508.3427892,20037508.3427892],
      "tileWidth": 256,
      "tileHeight": 256,
      "matrixWidth": 8,
      "matrixHeight": 8
    }
    ...
  ]
}
=================
