[[rc_tileSets-list]]
== Requirement Class "TileSets List"

=== Overview

[[tiles-core-overview]]

include::requirements/requirements_class_tilesets-list.adoc[]

This class defines a resource called TileSets that provided access to the available tilesets for a resource. It also defines a relation type to link to tileset resources. This class does not specify the path for a tileSet list. Refer to the <<rc_datasetTileSets>> and <<rc_geoDataResourceTileSets>> classes that describes two complementary mechanisms to associate tileSets to datasets and to geospatial data resources respectively.

=== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific Web API / server, the Web API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of URIs to conformance classes.

include::requirements/tilesets-list/REQ_conformance-success.adoc[]

If the server declares also conformity to OGC API - Common or to http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0], then it has to consider the OGC API - Common requirements for declaring conformance, i.e. the use of a the conformance page. In the JSON format the conformance page is an array of URIs following the schema defined in the OGC API - Common or in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0]. Below is an example fragment of a conformance information page of an API conformant to OGC API - Common and OGC API - Tiles.

[[ConformancePageTilesets]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tilesets-list"
  ]
}
=================

=== Tilesets
A tilesets resource represents a list of sets of tiles each one belonging to a particular TileMatrixSet. The resource return the necessary metadata to enable a client application to formulate a tile request.

==== Tilesets path
This class does not specify the path to a tileSet list. Refer to the <<rc_datasetTileSets>> and <<rc_geoDataResourceTileSets>> classes that describes two complementary mechanisms to associate tileSets to datasets and to geospatial data resources respectively.

==== Response

A successful GET response to a list of tilesets resource will respond with a data structure that lists the tileset URLs available (one for each Tile Matrix Set supported).

include::requirements/tilesets-list/REQ_tileset-links.adoc[]


[[TilesetsTilesLinkResponseExample]]
.Example of a tilesets list response
=================
[source,JSON]
{
  "tilesets": [
    ...
    {
      "tileMatrixSetURI" : "http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad",
      "dataType" : "vector",
      "links" : [
         {
           "rel": "self",
           "href": "http://data.example.com/collections/buildings/tiles/WebMercatorQuad",
           "type": "application/json"
         },
         {
           "rel": "http://www.opengis.net/def/rel/ogc/1.0/tiling-scheme",
           "href": "http://data.example.com/tileMatrixSets/WebMercatorQuad",
           "type": "application/json"
         }
      ]
   }
   ...
  ]
}
=================

include::recommendations/tilesets-list/REC_tileset-title.adoc[]

include::recommendations/tilesets-list/PER_tilesets-api.adoc[]
