[[rc_tileSet]]
== Requirement Class "TileSet"

=== Overview

[[tile-set-overview]]

include::requirements/requirements_class_tileset.adoc[]

This is a building block for the an OGC API that describes the TileSet resource and how to retrieve a tile from a tileset

Defines the response of a TileSet GET request (but not the path or the link for the request).
The response has two formats: tilejson and OGC json. The OGC json includes tilematrixset links, a central point (optional), a links to the URI template to individual tiles, and the geospatial data resources involved in the creation of the tiles (optional), and other metadata (including attribution; optional)
Defines how to formulate a request for individual tiles and how the response will look like (success and failure)

**TBD**

This is a building block for the an OGC API that is able to provide geospatial data resources. When applying the building block to a geospatial data resource, it becomes available as tiles. The server can select which resources are available as tiles and will advertise which resources are available as tiles.

This building block does not specify how to get an API definition, the conformance class list or the geospatial data resources lists. The standard assumes that the first two are defined by an API specification (e.g. OGC API Common) and the later by an OGC API for geospatial data resource (e.g. OGC API - Features).

The core of the OGC API - Tiles core draft specification does not mandate the inclusion of an explicit definition of any TileMatrixSet. This draft specification assumes that clients and services know about the eight TileMatrixSets defined in OGC 17-083r2 annex D (or compatible future update of it) and there is no need to define new TileMatrixSets. An extension to the core provides the capability to include definitions of flexible TileMatrixSets that are explicitly defined.

This draft specification assumes that data is organized into one or more geospatial data resources (e.g. the "collections" in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core]). Geospatial data resources are referenced using URIs.

This document does not specify any requirements for the type of geospatial data resource that should be supported. Provided that the geospatial data resources can be organized into tiles, they can be supported regardless of whether they are features, coverages, a resource that does not represent data per-se (e.g. an annotation) and so forth. The resource path replaces the concept of layer in WMS and WMTS. In this core tiles can be generated from only one geospatial data resource (tiles that are generated as a combination of geospatial data resources will be defined as an extension).

Accessing the geospatial data resource content (other than as tiles) or its descriptions is out of the scope of this draft specification. If a description of the geospatial data resource exists and it has a mechanism to add links to it, this specification will indicate the need to add a link to the tile description.

The tile description will include metadata about tiles as well as links to other resources including at least one with a template to get individual tiles.

**End of TBD**

=== Declaration of conformance classes
To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of links.

include::requirements/tileset/REQ_conformance-success.adoc[]

If the server declares also conformity to OGC API - Common or to http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0], then it has to consider the OGC API - Common requirements for declaring conformance, i.e. the use of a the conformance page. In the JSON format the conformance page is an array of links following the link schema defined in the OGC API - Common or in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0]. Below is an example fragment of a conformance information page of an API conformant to OGC API - Common and OGC API - Tiles.

[[ConformancePageTileset]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset"
  ]
}
=================

=== Tileset resource
A tileset resource represents the set of tiles that belongs to a particular tilematrixset. The resource contains the necessary metadata to enable a client application to formulate a tile request.

==== Tileset path

This class does not specify the path for a tileSet. Generally, TileSet resources are linked from a Tilesets resource. Refer to the TileSets class to know how TileSets can link to TileSet resources. Refer to the DatasetTileSets and GeoDataResourceTileSets classes that describes two mechanisms to associate tileSets to datasets and to geospatial data resources respectively.

==== Response
A successful GET response to a tileset resource will be a data structure with the specific information necessary to build a complete GET request to the tiles representing the geospatial data resource.

include::requirements/tileset/REQ_tileset-description.adoc[]

include::recommendations/tileset/REC_tmxslink.adoc[]

Clients or servers are not required to support a specific default TileMatrixSet.

The values of TileMatrixSetURI correspond to URIs pointing to the OGC TileMatrixSets registry is available at http://opengis.net/def/tms

NOTE: The OGC TileMatrixSets registry is based on the OGC Two Dimensional Tile Matrix Set standard.

//include::requirements/tileset/REQ_tile-template.adoc[]

NOTE: The geospatial data resource URL is expected to be the first part of the URL template (presented by the '...' in the previous note) but this standard does not mandate this.

include::recommendations/tileset/REC_sourcelink.adoc[]



[[TilesetTilesLinkResponseExample]]
.Example of a tileset response
=================
[source,JSON]
{
  ...
  "tileMatrixSetURI": "http://www.opengis.net/def/tilematrixset/OGC/1.0/WorldMercatorWGS84Quad",
  "dataType": "map",
  "links": [
    ...
    {
     "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad",
     "rel": "self",
     "type": "application/json",
    },
    {
     "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad/{tileMatrix}/{tileRow}/{tileCol}.png",
     "templated": true,
     "rel": "item",
     "type": "image/png",
    }
   ...
  ],
  "tileMatrixSetLimits":
  [
    { "tileMatrix" : "0", "minTileRow" : 0, "maxTileRow" : 0, "minTileCol" : 0, "maxTileCol" : 0 },
    { "tileMatrix" : "1", "minTileRow" : 0, "maxTileRow" : 0, "minTileCol" : 1, "maxTileCol" : 1 },
    { "tileMatrix" : "2", "minTileRow" : 1, "maxTileRow" : 1, "minTileCol" : 2, "maxTileCol" : 2 },
    { "tileMatrix" : "3", "minTileRow" : 3, "maxTileRow" : 3, "minTileCol" : 4, "maxTileCol" : 4 },
    ...
  ]
}
=================

NOTE: The use of "templated" is inspired by the JSON Hypertext Application Language (HAL), https://tools.ietf.org/html/draft-kelly-json-hal-08

The following table explains the meaning of the URI template variables.

[#URL_template_tile_core,reftext='{table-caption} {counter:table-num}']
.URI template variables for tiles and valid values
[cols="30,35,70",options="header"]
!===
|URL template variable |Meaning |Possible values
|TileMatrix |tile matrix identifier |Identifier of the tile matrix (representing a zoom level, a.k.a. a scale) listed in the TileMatrixSet definition
|TileRow |row index of tile matrix	|A non-negative integer between 0 and the MatrixHeight – 1. If there is a TileMatrixSetLimits the value is limited between MinTileRow and MaxTileRow
|TileCol |column index of tile matrix	|A non-negative integer between 0 and the MatrixWidth – 1. If there is a TileMatrixSetLimits the value is limited between MinTileCol and MaxTileCol
!===

NOTE: The use of "templated" is inspired by the JSON Hypertext Application Language (HAL), https://tools.ietf.org/html/draft-kelly-json-hal-08

NOTE: TileJSON is an alternative for a tileset description document. See Annex TBD for more details about this format. Currently this specification only supports WebMercatorQuad TileMatrixSet and the reference to it is implicit. The version 3 of this specification provides a mechanism to cite data sources too.

=== A tile
A tile resource is a geospatial resource of a fragment of a more bigger geospatial data resource that is spatially constrained at the boundaries of the selected tile in a tile matrix set.

==== Tile path and link
As described before a tile path is obtained by extracting a tile URL templated from one of the links with `rel`: `item` in tileset description document and substituting the templated variables of with valid values.

==== Operation
This operation allows retrieving a single tile that represents information coming from geospatial data resources.

include::requirements/tileset/REQ_tc-op.adoc[]

Typical geospatial data resources that can be retrieved as tiles are: vector features (available at `/collections/{collectionId}/items` in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core], for which it is recommended to provide tilesets at `/collections/{collectionId}/tiles`),
maps (specified in OGC - API Maps) or coverages (specified in OGC API - Coverages).

include::recommendations/tileset/REC_tc-op.adoc[]

The supported encodings, or more precisely the media types of the supported encodings, can be determined from the API definition. The desired encoding is selected using HTTP content negotiation.

The core of the OGC API - Tiles standard provides a mechanism to select and retrieve a tile in a TileMatrixSet.
A resource will be available providing metadata for each available tileset, including a link to either a TileMatrixSet registered in the OGC TileMatrixSet registry,
or to a custom TileMatrixSet definition.

==== Parameter tileMatrix
include::requirements/tileset/REQ_tc-tilematrix-definition.adoc[]

==== Parameter tileRow
include::requirements/tileset/REQ_tc-tilerow-definition.adoc[]

==== Parameter tileCol
include::requirements/tileset/REQ_tc-tilecol-definition.adoc[]

==== Response

A successful response to a tile GET operation will be consistent with the media type of resource requested. This draft specification does not impose any media type or file format. For example:

* For features the media type may be GeoJSON or Mapbox Vector Tiles;
* For coverages the response may be a GeoTIFF;
* For maps the response may be a JPEG or a PNG.

include::requirements/tileset/REQ_tc-success.adoc[]

include::recommendations/tileset/PER_tc-core-tile-encoding.adoc[]

Normally, the content partially outside the tile bounding box will be clipped at the extent of the bounding box. This can be done efficiently when tiles are in raster format (e.g. map tiles). However, tiles containing features in vector format may not clip features that are partially outside to ensure continuity of features or for performance.

include::recommendations/tileset/REC_tc-success-scale.adoc[]

include::recommendations/tileset/REC_tc-deepfullempty.adoc[]

To enable search engines to easily discover the content offered by an implementation of OGC API - Tiles, as well as to enable web browsers to easily display the content offered by the APIs, this standard allows for responses to operations to be encoded in HTML.

include::recommendations/tileset/PER_tc-core-html.adoc[]

==== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

If the parameters values `tileMatrix`, `tileRow`, `tileCol` are out-of-range, the status code of the response will be `404`.

If the tile has no content due to lack of data in the area, but within the data resource's tile matrix sets limits, the status code of the response will be either 204, indicating an empty tile, or 200 with an empty file (which or may not be zero bytes, depending on the output format).
