[[rc_collections-selection]]
== Requirement Class "Geo Data Resource Selection"

=== Overview

[[tiles-collections-selection-overview]]

include::requirements/requirements_class_collections-selection.adoc[]

In a Web API providing access to a complex dataset formed by several geospatial data resources, there are reasons for being selective in the amount of information include when requesting an operation affecting the dataset. Here we define how to include a query parameter to filter the amount of information provided by the dataset (e.g. which geospatial data resources are involved in the creation of some derived resource).

=== General
include::recommendations/collections-selection/REC_api-common.adoc[]

This building block stays flexible and does not require implementation OGC API - Common, allowing for other API architectures outside the OGC API framework to adopt it. However, a server under the OGC APIs is expected to implement OGC API - Common. If so, in practice, this means that the landing page and the conformance page follow OGC API - Common core and collections requirement classes when used. Temporarily, it is also possible to combine this building block with http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] that is not tied to OGC API - Common.

=== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of URIs to conformance classes.

include::requirements/collections-selection/REQ_conformance-success.adoc[]

If the server declares also conformity to OGC API - Common or to http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0], then it has to consider the OGC API - Common requirements for declaring conformance, i.e. the use of a the conformance page. In the JSON format the conformance page is an array of URIs following the schema defined in the OGC API - Common or in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0]. Below is an example fragment of a conformance information page of an API conformant to OGC API - Common and OGC API - Tiles.

[[ConformancePageDataSelection]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/dataset",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset/collections-selection"
  ]
}
=================

=== Selection of collections

==== Operation
By default, the  geospatial data resources included in the dataset is undefined but it is supposed to represent the dataset. This class adds a mechanism to select the geospatial data resources that are going to be used to create the a derived resource (e.g. maps or tiles). In practice this give use the capability to create resources involving from more than one geospatial data resource.

==== Parameter Resources
include::requirements/collections-selection/REQ_query-collections.adoc[]

When this parameter refers to more that one geospatial data resource, this parameter will use the
comma (",") as the separator between the resource identifiers in the list. Additional white space will not be used to delimit list items. If a geospatial data resource identifier includes a space or comma, it shall be escaped using the URL encoding rules (IETF RFC 2396).

==== Error conditions

If the value of the parameter `collections` contains a resource id of URI that does not exist on the API, the status code of the response is 400.

If the value of the parameter `collections` has a wrong format or combines one of more geospatial data resources that are not compatible (e.g. they do not have a compatible value specified by other parameters in the request), the status code of the response is 400.
