[[rc_tiles_core]]
== Requirements Class "Core"

[[core-overview]]

include::requirements/requirements_class_core.adoc[]

The core requirements class is designed as a very generic requirements class that describes an HTTP GET operation, as well as its response, to retrieve tiles from a tileset which can be described by the https://docs.ogc.org/is/17-083r4/17-083r4.html[OGC Two Dimensional Tile Matrix Set and Tile Set Metadata 2.0] standard. It introduces the idea of URI templates and variables associated with the TileMatrix, TileRow and TileCol concepts defined in the https://docs.ogc.org/is/17-083r4/17-083r4.html[OGC Two Dimensional Tile Matrix Set and Tile Set Metadata 2.0] standard but it does not prescribe a particular path or template form for the URL of those tiles.

This requirements class by itself only concerns the individual tiles and does not describe the tileset as a whole. It is highly recommended that the implementer of a Web API implements support for tileset metadata in conjunction with the core requirements class as it provides important information to clients. This can be done by also implementing the Requirements Class "Tileset" (<<rc_tileSet>>) or integrating within another API providing this capability through another mechanism.

=== A tile
A tile resource is a geospatial resource presenting a fragment of a much bigger geospatial data resource that is spatially constrained at the boundaries of the selected tile in a tile matrix set.

==== Operation
This operation supports the retrieval of a single tile that represents information coming from geospatial data resources.

include::requirements/core/REQ_tc-op.adoc[]

Typical geospatial data resources that can be retrieved as tiles are: vector features
(available at `/collections/{collectionId}/items` in https://docs.ogc.org/is/17-069r4/17-069r4.html[OGC API - Features - Part 1: Core],
for which it is recommended to provide tilesets at `/collections/{collectionId}/tiles`),
maps (specified in OGC API - Maps) or coverages (specified in OGC API - Coverages).

include::recommendations/core/REC_tc-op.adoc[]

The API implementation can determine the supported encodings, or more precisely the media types of the supported encodings, from the Web API definition, or from the conformance declaration (see <<rc_data_encodings>>).
The desired encoding is selected using HTTP content negotiation.

The core of the OGC API - Tiles standard provides a mechanism to select and retrieve a tile in a TileMatrixSet that is agreed between the client and server. This core requirements class does not discuss the details of how the client and service agree on which TileMatrixSet they use.

==== Parameter tileMatrix
include::requirements/core/REQ_tc-tilematrix-definition.adoc[]

==== Parameter tileRow
include::requirements/core/REQ_tc-tilerow-definition.adoc[]

==== Parameter tileCol
include::requirements/core/REQ_tc-tilecol-definition.adoc[]

==== Parameter tileMatrixSetId (optional)
include::recommendations/core/PER_tc-tilematrixsetid-definition.adoc[]


==== Response

A successful response to a tile GET operation will be consistent with the media type of the resource requested. This Standard does not impose any media type or file format. Examples of common media types are:

* For features, the media type of the response may be GeoJSON (application/geo+json) or Mapbox Vector Tiles (application/vnd.mapbox-vector-tile);
* For coverages, the media type of the response  may be GeoTIFF (image/tiff) or netCDF (application/netcdf or application/x-netcdf);
* For maps, the media type of the response may be JPEG (image/jpeg) or a PNG (image/png).

include::requirements/core/REQ_tc-success.adoc[]

include::recommendations/core/PER_tc-tile-encoding.adoc[]

Normally, the content partially outside the tile bounding box will be clipped at the extent of the bounding box. This can be done efficiently when tiles are in raster format (e.g., map tiles).
However, tiles containing features in vector format may not clip features that are partially outside, or clip to a slightly enlarged bounding box (a buffer), to ensure continuity of features or for performance.

include::recommendations/core/REC_tc-success-scale.adoc[]

include::recommendations/core/REC_tc-deepfullempty.adoc[]

To enable search engines to easily discover the content offered by an implementation of OGC API - Tiles, as well as to enable web browsers to easily display the content offered by the Web APIs, this standard allows for responses to operations to be encoded in HTML.

include::recommendations/core/PER_tc-html.adoc[]

==== Error conditions

A general summary of the HTTP status codes can be found in https://docs.ogc.org/is/17-069r4/17-069r4.html[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common — Part 1: Core.

include::requirements/core/REQ_tc-error.adoc[]

=== Declaration of conformance classes
To support "generic" clients wishing to access multiple implementations of OGC API Standards and extensions - and not "just" a specific Web API / server,
the Web API has to declare the conformance classes it implements and conforms to.

==== Response

The conformance declaration mainly consists of a list of links.

include::requirements/core/REQ_tc-conformance-success.adoc[]

If the server also declares conformity to OGC API - Common - Part 1: Core or to https://docs.ogc.org/is/17-069r4/17-069r4.html[OGC API - Features - Part 1: Core, version 1.0], then it has to consider the OGC API - Common requirements for declaring conformance, i.e. the use of a conformance declaration page. In the JSON format the conformance declaration page is an array of links following the link schema defined in the OGC API - Common or in https://docs.ogc.org/is/17-069r4/17-069r4.html[OGC API - Features - Part 1: Core, version 1.0] standards. Below is an example fragment of a conformance declaration page of a Web API conformant to OGC API - Common and OGC API - Tiles.

[[ConformancePageTileset]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core"
  ]
}
=================
