== Terms and Definitions
This document uses the terms defined in Sub-clause 5.3 of https://portal.opengeospatial.org/files/?artifact_id=38867[OGC Web Services Common] (OGC 06-121r9), which is based on the ISO/IEC Directives, Part 2, Rules for the structure and drafting of International Standards. In particular, the word “shall” (not “must”) is the verb form used to indicate a requirement to be strictly followed to conform to this standard.

This document also uses terms defined in Sub-clause "Terms and Definitions" of OGC API - Common, Part 1: core.

For the purposes of this document, the following additional terms and definitions apply.

=== *geospatial data resource*
web resource that consists in a set of geospatial data

NOTE: Most of the resources provided by OGC API _collections_ are considered geospatial data resources. Maps and coverages are also considered geospatial data resources.

=== *geospatial aspect*
web resource that represents a component of geospatial information (metadata, schemas,...) or geospatial data in a particular data model (e.g., feature items, tiles, coverages,...) of a more generic geospatial data resource (e.g., a collection)

NOTE: Do not confuse this with a web resource representation. While resource representations share the same path and are selected by format negotiation, geospatial aspects use different paths. Commonly a geospatial aspect is a child path of a geospatial data resource

=== *map tile*

tile that contains information in a gridded form. Commonly the values of the grid represent colors of each cell in the grid for immediate pictorial representation on rendering devices, but can also be coverage subsets.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set

NOTE: Map tiles are generated in combination with the OGC API - Maps. This tiles are sometimes refered as _raster tiles_

=== *tile*

geometric shape with known properties that may or may not be the result of a tiling (tessellation) process. A tile consists of a single connected "piece" without "holes" or "lines" (topological disc).

NOTE: From OGC 19-014r1: Core Tiling Conceptual and Logical Models for 2D Euclidean Space

small rectangular representation of geographic data, often part of a set of such elements, covering a tiling scheme and sharing similar information content and graphical styling. A tile can be uniquely defined in a tile matrix by one integer index in each dimension. Tiles are mainly used for fast transfer (particularly in the web) and easy display at the resolution of a rendering device. Tiles can be grid based pictorial representations, coverage subsets, or feature based representations (e.g., vector tiles).

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set

=== *tile matrix*

grid tile set scheme defining how space is partitioned into a set of regular conterminous tiles at a fixed scale giving tile scheme to each tile.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set (modified).

NOTE: For the purposes of this document a tile matrix is restricted to a tessellation of the space that resembles a matrix in a 2D space characterized by a matrix width (columns) and a matrix height (rows).

=== *tile matrix set*

tile set scheme composed by collection of tile matrices defined at different scales covering approximately the same area and having a common coordinate reference system.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set but modified.

=== *tile scheme*
scheme  that  defines  the  unique  properties  of  each  individual  tile  in  a  tile  set.  These  properties include a unique identifier for each tile, the tile origin, and the extent of the tile.

NOTE: From OGC 19-014r1: Core Tiling Conceptual and Logical Models for 2D Euclidean Space

=== *tile set*

set of tiles - a collection of subsets of the space being partitioned.

NOTE: From OGC 19-014r1: Core Tiling Conceptual and Logical Models for 2D Euclidean Space

NOTE: For the purposes of this document, a tile set is a series of actual tiles containing data and following a common tile set scheme.

=== *tile set scheme*

scheme that defines how space is partitioned into individual tiled units. A tiling scheme defines the spatial reference system, the geometric properties of a tile, which space a uniquely identified tile occupies, and reversely, which unique identifier corresponds to a space satisfying the geometric properties to be a tile.

NOTE: From OGC 19-014r1: Core Tiling Conceptual and Logical Models for 2D Euclidean Space

NOTE: A tile set scheme can be defined on top of a CRS as well as other spatial reference systems such as DGGS and other organizations including irregular ones. In this document, only tile set schemes based on CRSs are supported.

=== *vector tile*

tile that contains vector information that has been simplified at the tile scale resolution and clipped by the tile boundaries.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set but modified.

=== *Web API*

API using an architectural style that is founded on the technologies of the Web [source: OGC API - Features - Part 1: Core]

NOTE: See link:https://www.w3.org/TR/dwbp/#APIHttpVerbs[Best Practice 24: Use Web Standards as the foundation of APIs] (W3C Data on the Web Best Practices) for more detail.
