[[rc_tileSets-list]]
== Requirement Class "TileSets List"

=== Overview

[[tiles-core-overview]]

include::requirements/requirements_class_tilesets-list.adoc[]

This class defines a resource called TileSets that provided access to the available tilesets for a resource. It also defines a relation type to link to tileset resources. This class does not specify the path for a tileSet list. Refer to the <<rc_datasetTileSets>> and <<rc_geoDataResourceTileSets>> classes that describes two complementary mechanisms to associate tileSets to datasets and to geospatial data resources respectively.

=== Tilesets list
A tilesets resource represents a list of sets of tiles each one belonging to a particular TileMatrixSet. The resource return the necessary metadata to enable a client application to formulate a tile request.

==== Tilesets path
This class does not specify the full path to a tileSet list but requires that it ends with `/tiles`. Refer to the <<rc_datasetTileSets>> and <<rc_geoDataResourceTileSets>> classes that describes two complementary mechanisms to associate tileSets to datasets and to geospatial data resources respectively.

include::requirements/tilesets-list/REQ_tileset-path.adoc[]

==== Response

A successful GET response to a list of tilesets resource will respond with a data structure that lists the tileset URLs available (one for each Tile Matrix Set supported).

include::requirements/tilesets-list/REQ_tileset-links.adoc[]


[[TilesetsTilesLinkResponseExample]]
.Example of a tilesets list response
=================
[source,JSON]
{
  "tilesets": [
    ...
    {
      "tileMatrixSetURI" : "http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad",
      "dataType" : "vector",
      "links" : [
         {
           "rel": "self",
           "href": "http://data.example.com/collections/buildings/tiles/WebMercatorQuad",
           "type": "application/json"
         },
         {
           "rel": "http://www.opengis.net/def/rel/ogc/1.0/tiling-scheme",
           "href": "http://data.example.com/tileMatrixSets/WebMercatorQuad",
           "type": "application/json"
         }
      ]
   }
   ...
  ]
}
=================

include::recommendations/tilesets-list/REC_tileset-title.adoc[]

include::recommendations/tilesets-list/PER_tilesets-api.adoc[]
