[[rc_collections-selection]]

== Requirements Class "Collections Selection"

=== Overview

include::requirements/requirements_class_collections-selection.adoc[]

[[rm_collections-selection]]

In a server providing access through a Web API to a complex dataset formed by several geospatial data resources, selecting specific sub-resources of interest when requesting data from this dataset can be useful.
This requirements class defines how to include a query parameter when requesting a resource (e.g., dataset tiles) to specify which geospatial data resources (a.k.a. collections) should be used to generate the response.

This Requirements Class can be implemented e.g. in conjunction with the Requirements Class "Dataset Tilesets" (<<rc_datasetTileSets>>) or in conjunction with an equivalent requirements class from _OGC API - Maps_.

=== Operation

By default, the geospatial data resources to be included in the dataset tiles responses are unspecified but should represent the entire dataset.
This Class adds a mechanism to select the geospatial data resources to be used to generate the derived resources (e.g., maps or tiles).
In practice this enables the capability to generate resources involving more than one geospatial data sub-resource.

[[req_collections-selection_parameter-collections]]
==== Parameter `collections`

include::requirements/collections-selection/REQ_query-collections.adoc[]

When this parameter refers to more than one geospatial data resource, this parameter will use the
comma (",") as the separator between the resource identifiers in the list. Additional white space will not be used to delimit list items. If a geospatial data resource identifier includes a space or comma, it shall be escaped using the URL encoding rules (IETF RFC 2396).

[[per_collections-selection_valid-collections]]
include::recommendations/collections-selection/PER_valid-collections.adoc[]

[[req_collections-selection-response]]
==== Response

include::requirements/collections-selection/REQ_collections-response.adoc[]

==== Error conditions

If the value of the parameter `collections` contains a resource id of URI that does not exist in the Web API implementation, the status code of the response is 400.

If the value of the parameter `collections` has a wrong format or combines one or more geospatial data resources that are not compatible (e.g., they do not have a compatible value specified by other parameters in the request), the status code of the response is 400.
