.Preface

This document defines the _OGC API — Tiles — Part 1: Core_ Standard. A Web API conforming to this Standard can serve tiles of spatially referenced data or maps with predefined content, extent, and resolution. Suggested additions, changes and comments on this standard are welcome and encouraged. Such suggestions may be submitted using the issues log on the GitHub repository: https://github.com/opengeospatial/ogcapi-tiles .

////
*OGC Declaration*
////

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.

[abstract]
== Abstract

_OGC API — Tiles_ Standard defines building blocks for implementing Web APIs that support the retrieval of tiled geospatial information. 
A Web API is an [.underline]#application programming interface# for either a [.underline]#web server# or a [.underline]#web browser# [Wikipedia, 2022].
The OGC suite of Web APIs is an extensible framework for building HTTP based services that can be accessed in different applications on different platforms such as the web, windows, mobile etc.
_OGC API — Tiles_ Standard specifies how different forms/types of geospatial resources are supported, such as tiles of vector features (“vector tiles”), coverages, and maps (or imagery). Although OGC API - Tiles can be used independently, the building blocks can be combined with other OGC API Standards for additional capabilities or increased interoperability for specific types of data. 
The _OGC API — Tiles_ references the OGC Two-Dimensional Tile Matrix Set (TMS) and Tileset Metadata Standard [OGC 17-083r4]. 
That Standard defines logical models and encodings for specifying tile matrix sets and describing tile sets. 
A tile matrix set is a tiling scheme that enables an application to partition and index space based on a set of regular grids defined for multiple scales in a Coordinate Reference System (CRS).

The _OGC API - Tiles_ Standard is a successor to the OGC’s Web Map Tile Service (WMTS) Standard. 
Instead of a fixed Web interface, OGC API — Tiles focuses on simple reusable REST API building blocks which can be described using the OpenAPI specification. 
Whereas WMTS focused on map tiles, the _OGC API — Tiles_ Standard is designed to support any form of tiled data.
<<<<<<< HEAD

=======
>>>>>>> 31ad632ac70e475a2f8a8b8588db9bb7cca9e79f

== Submitters

All questions regarding this submission should be directed to the editor or the submitters:

[%unnumbered]
|===
| *Name* | *Affiliation*
| Joan Masó | Universitat Autònoma de Barcelona (CREAF)
| Chuck Heazel | Heazel Tech
| Jeff Harrison | US Army Geospatial Center (AGC)
| Jérôme Jacovella-St-Louis| Ecere Corporation
| Satish Sankaran | Esri
|===
