
[[rc_core]]
== Requirement Class "Core"

[[core-overview]]

include::requirements/requirements_class_core.adoc[]

The core conformance class describes the HTTP GET operation, as well as its response, to retrieve tiles from a tileset which can be described by the 2D Tile Matrix Set standard.
It does not prescribe a particular path or template form for the URL of those tiles, but the tileset conformance class does.

A mechanism other than the tileset conformance class can be used to describe the tileset in conjunction with the core conformance class, such as TileJSON.
See Annex TBD for more details about this format.
Currently TileJSON specification only supports WebMercatorQuad TileMatrixSet and the reference to it is implicit, while
version 3 provides a mechanism to cite data sources as well.

=== Declaration of conformance classes
To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server,
the API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of links.

include::requirements/core/REQ_conformance-success.adoc[]

If the server declares also conformity to OGC API - Common or to http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0],
then it has to consider the OGC API - Common requirements for declaring conformance, i.e. the use of a the conformance page.
In the JSON format the conformance page is an array of links following the link schema defined in the OGC API - Common or in
http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0].
Below is an example fragment of a conformance information page of an API conformant to OGC API - Common and OGC API - Tiles.

[[ConformancePageCore]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core"
  ]
}
=================

Clients or servers are not required to support a specific default TileMatrixSet.

The OGC TileMatrixSets registry is available at http://opengis.net/def/tms.

=== A tile
A tile resource is a geospatial resource of a fragment of a more bigger geospatial data resource that is spatially constrained at the boundaries of the selected tile in a tile matrix set.

==== Operation
This operation allows retrieving a single tile that represents information coming from geospatial data resources.

include::requirements/core/REQ_tc-op.adoc[]

Typical geospatial data resources that can be retrieved as tiles are: vector features
(available at `/collections/{collectionId}/items` in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core],
for which it is recommended to provide tilesets at `/collections/{collectionId}/tiles`),
maps (specified in OGC - API Maps) or coverages (specified in OGC API - Coverages).

include::recommendations/tileset/REC_tc-op.adoc[]

The supported encodings, or more precisely the media types of the supported encodings, can be determined from the API definition. The desired encoding is selected using HTTP content negotiation.


The core of the OGC API - Tiles standard provides a mechanism to select and retrieve a tile in a TileMatrixSet.

==== Parameter tileMatrix
include::requirements/core/REQ_tc-tilematrix-definition.adoc[]

==== Parameter tileRow
include::requirements/core/REQ_tc-tilerow-definition.adoc[]

==== Parameter tileCol
include::requirements/core/REQ_tc-tilecol-definition.adoc[]

==== Response

A successful response to a tile GET operation will be consistent with the media type of resource requested. This draft specification does not impose any media type or file format. For example:

* For features the media type may be GeoJSON or Mapbox Vector Tiles;
* For coverages the response may be a GeoTIFF;
* For maps the response may be a JPEG or a PNG.

include::requirements/core/REQ_tc-success.adoc[]

include::recommendations/tileset/PER_tc-core-tile-encoding.adoc[]

Normally, the content partially outside the tile bounding box will be clipped at the extent of the bounding box. This can be done efficiently when tiles are in raster format (e.g. map tiles). However, tiles containing features in vector format may not clip features that are partially outside to ensure continuity of features or for performance.

include::recommendations/tileset/REC_tc-success-scale.adoc[]

include::recommendations/tileset/REC_tc-deepfullempty.adoc[]

To enable search engines to easily discover the content offered by an implementation of OGC API - Tiles, as well as to enable web browsers to easily display the content offered by the APIs, this standard allows for responses to operations to be encoded in HTML.

include::recommendations/tileset/PER_tc-core-html.adoc[]

==== Error conditions

A general summary of the HTTP status codes can be found in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] as well as in OGC API - Common.

If the parameters values `tileMatrix`, `tileRow`, `tileCol` are out-of-range, the status code of the response will be `404`.

If the tile has no content due to lack of data in the area, but is within the data resource's tile matrix sets limits, the status code of the response will be either 204, indicating an empty tile, or 200 with an empty file (which or may not be zero bytes, depending on the output format).

[[rc_tileSet]]
== Requirement Class "TileSet"

=== Overview

[[tile-set-overview]]

include::requirements/requirements_class_tileset.adoc[]

The tileset conformance class provides a mechanism to describe a single tileset, for one particular geospatial data resource and tiled using one
according to one specific TileMatrixSet.
It also provides a mechanism to obtain a templated link to retrieve individual tiles as defined in the _core_ conformance class.

It describes the HTTP GET operation on a tileset resource and its response, but not a specific path.
The response provides metadata as per the 2D Tile Matrix Set and TileSet Metadata standard.

The essential elements of this metadata are:
- a link to the definition of the TileMatrixSet (either one registered in the OGC TileMatrixSet registry, or to a custom TileMatrixSet definition),
- a templated link (URI) to individual tiles,
- and a data type (indicating whether the tileset consists of vector, coverage or map tiles).

It may optionally also provide additional information, such as:
- the geospatial data resources involved in the creation of the tiles (potentially including links to OGC API collections),
- a schema of the available properties contained within the tiles,
- styles used to create the tiles,
- a central point on which a viewer may initially focus,
- attribution.

The explicit definition of a TileMatrixSet is only required for custom TileMatrixSet not registered in the OGC TileMatrixSet registry.
However, it is recommended that the API always provides a link to a local definition of the TileMatrixSets used.

Services and clients are encouraged to support as many of the TileMatrixSets defined in the OGC TileMatrixSet registry as possible to maximize
interoperability, but support is not required for any specific tile matrix set.
See also annexes D and H for TileMatrixSets defined and registered at the time of publication of this specification.

=== Declaration of conformance classes
To support "generic" clients wishing to access multiple OGC API standards and extensions - and not "just" a specific API / server,
the API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of links.

include::requirements/tileset/REQ_conformance-success.adoc[]

If the server declares also conformity to OGC API - Common or to http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0], then it has to consider the OGC API - Common requirements for declaring conformance, i.e. the use of a the conformance page. In the JSON format the conformance page is an array of links following the link schema defined in the OGC API - Common or in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0]. Below is an example fragment of a conformance information page of an API conformant to OGC API - Common and OGC API - Tiles.

[[ConformancePageTileset]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset"
  ]
}
=================

=== Tileset resource
A tileset consists of a set of tiles obtained by partitioning geospatial data according to a particular TileMatrixSet.
The tileset description resource contains all the information necessary for a client application to request tiles from that tileset.

==== Tileset path

This class does not specify a full path to a tileSet. Generally, TileSet resources are linked from a Tilesetslist resource (see <<rc_tileSets-list>>).
Refer to the _tilesets list_ conformance class to know how to list available TileSets and link to individual TileSet resources.
Refer to the _dataset tilesets_ and _geodata tilesets_ conformance classes describing two mechanisms to associate list of tilesets to
OGC API dataset (landing page) and to geospatial data (collection) resources respectively.
It is expected that a tileset can be used as a building block in other APIs and on top of resources such as maps, features, coverages or any other geospatial resources that can benefit from tiling.

==== Response
A successful GET response to a tileset resource will be a data structure with the specific information necessary to build a complete GET request to the tiles representing the geospatial data resource.

include::requirements/tileset/REQ_tileset-description.adoc[]

include::recommendations/tileset/REC_tmxslink.adoc[]

Clients or servers are not required to support a specific default TileMatrixSet.

The values of TileMatrixSetURI correspond to URIs pointing to the OGC TileMatrixSets registry is available at http://opengis.net/def/tms

NOTE: The OGC TileMatrixSets registry is based on the OGC Two Dimensional Tile Matrix Set standard.

//include::requirements/tileset/REQ_tile-template.adoc[]

NOTE: The geospatial data resource URL is expected to be the first part of the URL template (presented by the '...' in the previous note) but this standard does not mandate this.

include::recommendations/tileset/REC_sourcelink.adoc[]



[[TilesetTilesLinkResponseExample]]
.Example of a tileset response
=================
[source,JSON]
{
  ...
  "tileMatrixSetURI": "http://www.opengis.net/def/tilematrixset/OGC/1.0/WorldMercatorWGS84Quad",
  "dataType": "map",
  "links": [
    ...
    {
     "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad",
     "rel": "self",
     "type": "application/json",
    },
    {
     "href": "http://data.example.com/collections/buildings/tiles/WorldMercatorWGS84Quad/{tileMatrix}/{tileRow}/{tileCol}.png",
     "templated": true,
     "rel": "item",
     "type": "image/png",
    }
   ...
  ],
  "tileMatrixSetLimits":
  [
    { "tileMatrix" : "0", "minTileRow" : 0, "maxTileRow" : 0, "minTileCol" : 0, "maxTileCol" : 0 },
    { "tileMatrix" : "1", "minTileRow" : 0, "maxTileRow" : 0, "minTileCol" : 1, "maxTileCol" : 1 },
    { "tileMatrix" : "2", "minTileRow" : 1, "maxTileRow" : 1, "minTileCol" : 2, "maxTileCol" : 2 },
    { "tileMatrix" : "3", "minTileRow" : 3, "maxTileRow" : 3, "minTileCol" : 4, "maxTileCol" : 4 },
    ...
  ]
}
=================

NOTE: The use of "templated" is inspired by the JSON Hypertext Application Language (HAL), https://tools.ietf.org/html/draft-kelly-json-hal-08

The following table explains the meaning of the URI template variables.

[#URL_template_tile_core,reftext='{table-caption} {counter:table-num}']
.URI template variables for tiles and valid values
[cols="30,35,70",options="header"]
!===
|URL template variable |Meaning |Possible values
|TileMatrix |tile matrix identifier |Identifier of the tile matrix (representing a zoom level, a.k.a. a scale) listed in the TileMatrixSet definition
|TileRow |row index of tile matrix	|A non-negative integer between 0 and the MatrixHeight – 1. If there is a TileMatrixSetLimits the value is limited between MinTileRow and MaxTileRow
|TileCol |column index of tile matrix	|A non-negative integer between 0 and the MatrixWidth – 1. If there is a TileMatrixSetLimits the value is limited between MinTileCol and MaxTileCol
!===

=== A tile
A tile resource is a fragment of a larger geospatial data resource that is spatially constrained at the boundaries of the selected tile in a tile matrix set.

==== Tile path and link
The path to a tile is obtained by extracting a tile URL templated from one of the links with "rel": "item" in the tileset description document and substituting the templated variables of with valid values.
