[[rc_collections-selection]]

In a Web API providing access to a complex dataset formed by several geospatial data resources, there are reasons for being selective in the amount of information included when requesting an operation affecting the dataset. This requirements class defines how to include a query parameter to a resource that depends on the root (e.g., a dataset tile) to filter the amount of information provided by the dataset (a.k.a,. by specifying which geospatial data resources (a.k.a., collections) are involved in the creation of some root derived resource).

This conformance class can be used in conjunction to the <<rc_datasetTileSets>> conformance class or in conjunction to an equivalent conformance class in the OGC API Maps.

=== General
include::recommendations/collections-selection/REC_api-common.adoc[]

This building block stays flexible and does not strictly require implementation OGC API - Common, allowing for other Web API architectures outside the OGC API framework to adopt it. However, a server under the OGC APIs is expected to implement OGC API - Common. If so, in practice, this means that the landing page and the conformance page follow OGC API - Common core and collections requirement classes when used. Temporarily, it is also possible to combine this building block with http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] that is not tied to OGC API - Common.

=== Declaration of conformance classes
To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific Web API / server, the Web API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of URIs to conformance classes. The actual conformance class name is defined in a subclause below.

If the server declares also conformity to OGC API - Common or to http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0], then it has to consider the OGC API - Common requirements for declaring conformance, i.e. the use of a the conformance page. In the JSON format the conformance page is an array of URIs following the schema defined in the OGC API - Common or in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0]. Below is an example fragment of a conformance information page of an Web API conformant to OGC API - Common and OGC API - Tiles.

=== Selection of collections

==== Operation
By default, the  geospatial data resources included in the dataset are undefined but it are supposed to represent the dataset. This class adds a mechanism to select the geospatial data resources that are going to be used to create the a derived resource (e.g., maps or tiles). In practice this give use the capability to create resources involving from more than one geospatial data resource.

==== Parameter Resources
[[req_collections-selection_resources-query]]

include::requirements/collections-selection/REQ_query-collections.adoc[]

When this parameter refers to more that one geospatial data resource, this parameter will use the
comma (",") as the separator between the resource identifiers in the list. Additional white space will not be used to delimit list items. If a geospatial data resource identifier includes a space or comma, it shall be escaped using the URL encoding rules (IETF RFC 2396).

==== Error conditions

If the value of the parameter `collections` contains a resource id of URI that does not exist on the Web API, the status code of the response is 400.

If the value of the parameter `collections` has a wrong format or combines one of more geospatial data resources that are not compatible (e.g., they do not have a compatible value specified by other parameters in the request), the status code of the response is 400.
