== Terms, definitions and abbreviated terms

=== Terms and definitions

==== process

_tile_ that contains information, often in a gridded form, where the values represent observations or measurements as a count, or quantity using some unit of measure

NOTE: Coverage tiles are generated in combination with _OGC API - Coverages_, and can also be generated by combining a subset (trim) and resampling operation. When stored in gridded form, these tiles are a type of _raster tiles_.
Usually, visualizing a coverage tile on a rendering device implies mapping those values to colors.

=== geospatial data resource
web resource that consists in a set of geospatial data

NOTE: In Web APIs implementing _OGC API - Common - Part 2: Geospatial data_, geospatial data resources are referred to as collections and are defined in the _collections_ conformance class.

=== geospatial aspect
web resource that represents a component of geospatial information (metadata, schemas...) or geospatial data accessed using a particular mechanism and data model (e.g., feature items, tiles, maps, coverages,...) of a more generic geospatial data resource (e.g., a collection)

NOTE: Not to be confused with a web resource representation. While resource representations share the same path and are selected by format negotiation, geospatial aspects use different paths. Commonly a geospatial aspect is a subpath of a geospatial data resource.

=== map tile

_tile_ that contains information in a gridded form where the values of cells are colors which can be readily displayed on rendering devices

NOTE: Map tiles are generated in combination with _OGC API - Maps_. These tiles are a type of _raster tiles_.

=== tile

geometric shape with known properties that may or may not be the result of a tiling (tessellation) process. A tile consists of a single connected "piece" without "holes" or "lines" (topological disc).

NOTE: From OGC 19-014r1: Core Tiling Conceptual and Logical Models for 2D Euclidean Space

In the context of a 2D _tile matrix_, a _tile_ is one of the rectangular regions of space, which can be uniquely identified by a row and a column integer indices, making up the tile matrix.

In the context of a geospatial data _tile set_, a _tile_ contains data for such a partition of space as part of an overall set of tiles for that tiled geospatial data.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set

NOTE: Tiles are useful to efficiently request, transfer, cache, display, store and process geospatial data for a specific resolution and area of interest, providing deterministic performance and scalability
for arbitrarily large datasets.

NOTE: Tiles can contain a variety of data types, such as grid-based pictorial representations (map tiles), coverage subsets (coverage tiles), or feature-based representations (vector tiles).

=== tile matrix

tiling grid in a given 2D coordinate reference system, associated to a specific scale and partitioning space into regular conterminous _tiles_, each of which being assigned a unique identifier

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set.

NOTE: Each tile of a tile matrix is uniquely identifiable by a row and a column integer indices. The number of rows is referred to as the _matrix height_, while the maximum number of columns is referred to
as the _matrix width_ (the number of columns can vary for different rows in _variable width tile matrices_).

=== tile matrix set

_tiling scheme_ consisting of a set of _tile matrices_ defined at different scales covering approximately the same area and having a common coordinate reference system.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set.

=== tile indexing scheme
scheme allowing to uniquely reference a _tile_ in a _tiling scheme_ by the use of a unique identifier (or set of identifiers), and reversely, which unique identifier (or unique set of identifiers) corresponds
to a space satisfying the geometric properties of a specific tile

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set

=== tile set

a set of _tiles_ resulting from tiling data according to a particular _tiling scheme_

NOTE: From OGC 19-014r1: Core Tiling Conceptual and Logical Models for 2D Euclidean Space, but adapted to clarify that in the context of this document, a tile set refers specifically to a set of tiles containing
data and following a common tiling scheme.

=== tiling scheme

scheme that defines how space is partitioned into individual _tiles_, potentially featuring multiple levels of detail (each tiling at a different granularity to reflect a different resolution or scale)

A tiling scheme defines the spatial reference system and the geometric properties of each tile defined by the scheme.
Those properties include which space each tile occupies, i.e. its extent, as well as a tile coordinate origin if a particular corner of origin convention is established.

NOTE: A tiling scheme can be defined on top of a CRS as well as other spatial reference systems such as DGGS and other organizations including irregular ones.
In this document, only tiling schemes based on CRSs are supported.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set

=== tile set metadata

additional metadata beyond the common properties defining the _tile set_. Such metadata could be an abstract, the owner, the author, or other common metadata. [OGC 19-014r3]

metadata describing common properties defining a _tile set_, layers and styles used to produce the tile set, the limits of the tile matrix with actual data and common metadata such as abstract, owner, author, etc.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set

=== vector tile

tile that contains vector information that has been generalized (simplified) at the tile scale resolution and clipped by the tile boundaries.

NOTE: From OGC 17-083r4: OGC Two Dimensional Tile Matrix Set

=== Web API

API using an architectural style that is founded on the technologies of the Web [source: OGC API - Features - Part 1: Core]

NOTE: See link:https://www.w3.org/TR/dwbp/#APIHttpVerbs[Best Practice 24: Use Web Standards as the foundation of APIs] (W3C Data on the Web Best Practices) for more detail.
