[[rc_datasetTileSets]]
== Requirement Class "Dataset Tile Sets"

=== Overview

[[tiles-dataset-tiles-overview]]

include::requirements/requirements_class_dataset-tilesets.adoc[]

Defines how to get tiles from the dataset (or datasets) represented by the services. it will tell the path to get a tilesets resources

**TBD**

In previous clauses tiles are produced from one, and only one geospatial data resource available in this API. This scenario is achieved by concatenating the tile path to the geospatial data resource.

This OGC API requirements class is an extension of the core requirements class that defines how to create tiles that combine one or more geospatial data resources in any way that is decided in the client side. This is achieved by having the tile path available at the root of the service.

It has been argued that this approach is too flexible. In an API that has several geospatial data resources, the number of potential combinations of geospatial data resources may be too big to be efficiently handle. If the implementers see a potential performance issue, they may not choose to declare conformity to this requirements class.

=== General

This building block stays flexible and does not require implementation of OGC API - Common, allowing for other API architectures outside the OGC API framework to adopt it. However, a server under the OGC APIs is expected to implement OGC API - Common. If so, in practice, this means that the landing page and the conformance page follow OGC API - Common - Part 1: Core.

=== API landing page

The landing page provides links to start exploring the resources offered by the API. It mainly consists of a list of links to root resources. This standard extension requires a new link in the landing page for getting a description of the URL that allows for retrieving tiles of the resources in the dataset

==== Response

include::requirements/dataset-tilesets/REQ_landingpage.adoc[]

In the landing page, in JSON format, the links follow the link schema defined in the OGC API - Common or in OGC API - Features v1. Below you can find an example fragment of the response to an OGC API - Tiles landing page showing the link to root tiles.

[[landingPageTilesRoot]]
.API Landing Page fragment that advertises the path to get tiles for more than one collection
=================
[source,JSON]
----
{
  links: [
    ...,
    {
       "href": "http://data.example.org/tiles",
       "rel": "tiles",
       "type": "application/json",
       "title": "Link to information on map tilesets from the dataset",
    }
  ]
}
----
=================

=== Declaration of conformance classes

==== Response

The conformance page mainly consists of a list of links.

include::requirements/dataset-tilesets/REQ_conformance-success.adoc[]

On the conformance page (typically in JSON format) the links follow the link schema defined in the OGC API – Common draft specification. The following is an example fragment from the response to an OGC API - Tiles conformance information page showing the support for dataset tilesets

[[ConformancePageTilesroot]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset"
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tilesets"
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/dataset-tilesets"
  ]
}
=================

=== tilesets
The response to the tiles description operation contains the necessary information to later formulate a tile request of tiles from more than one collection.

==== Operation

include::requirements/dataset-tilesets/REQ_operation.adoc[]

The request of this operation has no parameters.

==== Response
A successful response to a tilesets request is a data structure defined by the tilesets and tileset classes

=== Tiles
The Tilesets have information on how to retrieve a single tile representing a piece of information in the dataset in the way explained in the tileset class
