[[rc_datasetTileSets]]
== Requirement Class "Dataset Tile Sets"

=== Overview

[[tiles-dataset-tiles-overview]]

include::requirements/requirements_class_dataset-tilesets.adoc[]

This conformance class defines a mechanism to retrieve a list of tilesets for a dataset (a.k.a., a root resource) which may contain multiple geospatial data resources. It is used in conjunction with <<rc_tileSets-list>> that specifies the response to this GET request.

Combined with the <<rc_collections-selection>> conformance class, it is also possible to select specific geospatial data resources (collections) to be combined and retrieved as tiles. For retrieving the list of tilesets for only one collection, the <<rc_geoDataResourceTileSets>> can also be used if it is implemented.

If a Web API offers several geospatial data resources for a dataset, it may limit the number of collections that can be retrieved together, and/or provide a limited subset of the collections by default.

=== General
This conformance class describes how to serve tilesets for a dataset provided as Web API instance implementing  _OGC API - Common - Part 1_ requirement classes or https://docs.ogc.org/is/17-069r4/17-069r4.html[OGC API - Features - Part 1: Core, version 1.0] as an alternative.

=== Web API landing page

The landing page provides links to start exploring the resources offered by the Web API. It mainly consists of a list of links to root resources. This conformance class requires including in the landing page one or more link(s) to list(s) of tilesets available for the dataset.

==== Response

include::requirements/dataset-tilesets/REQ_landingpage.adoc[]

In the landing page, in JSON format, the links follow the link schema defined in the _OGC API - Common - Part 1: Core_ or in _OGC API - Features - Part 1: Core_ 1.0.
Below you can find an example fragment of the response to an _OGC API - Tiles_ landing page showing links to dataset tilesets.

[[landingPageTilesRoot]]
.Web API Landing Page fragment that advertises dataset tilesets
=================
[source,JSON]
----
{
  "links": [
    ...
    {
       "href": "http://data.example.org/tiles",
       "rel": "http://www.opengis.net/def/rel/ogc/1.0/tilesets-vector",
       "type": "application/json",
       "title": "List of available vector features tilesets for the dataset"
    },
    {
       "href": "http://data.example.org/tiles",
       "rel": "http://www.opengis.net/def/rel/ogc/1.0/tilesets-map",
       "type": "application/json",
       "title": "List of available map tilesets for the dataset"
    }
  ]
}
----
=================

include::recommendations/dataset-tilesets/REC_landingpage.adoc[]

=== Dataset tilesets
The dataset tilesets operation provides essential tileset metadata and links to tilesets resources allowing to request tiles from the dataset.

==== Operation

include::requirements/dataset-tilesets/REQ_operation.adoc[]

The request of this operation has no parameters.

==== Response
A successful response to a dataset tilesets list request is a list of tilesets as defined by the <<rc_tileSets-list>> and <<rc_tileSet>>.

=== Tiles
The <<rc_tiles_core>> defines how to retrieve a single tile from a tileset available for the dataset.

==== Response
The response is expected to represent the dataset as a whole.
In a Web API providing access to a complex dataset formed by several geospatial data resources, it can be useful to select specific sub-resources of interest when requesting data from this dataset.
This can be achieved with the use of the <<rc_collections-selection>> or as an automatic decision by the server.

include::recommendations/dataset-tilesets/REC_geodata-selection.adoc[]

include::recommendations/dataset-tilesets/PER_geodata-selection.adoc[]
