[[rc_geoDataResourceTileSets]]
== Requirement Class "Geo Data Resource TileSets"

=== Overview

[[tiles-core-overview]]

include::requirements/requirements_class_geodata-tilesets.adoc[]

The _geodata tilesets_ conformance class assumes that data is organized into one or more geospatial data resources
(e.g. the "collections" http://docs.opengeospatial.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial data]).
Geospatial data resources are referenced using URIs.

It will define how to specify the a link to the list of tilesets containing a representation of this geospatial data resource (path).

=== General
include::recommendations/geodata-tilesets/REC_api-common.adoc[]

This building block depends on _OGC API - Part 2: Geospatial data_, but stays flexible and does not require implementation of OGC API - Common - Part 1,
allowing for other API architectures outside the OGC API framework to adopt it.
However, a server under the OGC APIs is expected to implement OGC API - Common - Part 1.
If so, in practice, this means that the landing page and the conformance page follow OGC API - Common core requirement classes when used.
Temporarily, it is also possible to combine this building block with http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] that is not tied to OGC API - Common.

=== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of links.

include::requirements/geodata-tilesets/REQ_conformance-success.adoc[]

If the server declares also conformity to OGC API - Common or to http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0], then it has to consider the OGC API - Common requirements for declaring conformance, i.e. the use of a the conformance page. In the JSON format the conformance page is an array of links following the link schema defined in the OGC API - Common or in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0].
Below is an example fragment of a conformance information page of an API conformant to OGC API - Common and OGC API - Tiles.

[[ConformancePageGeoDataTilesets]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tilesets-list",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/geodata-tilesets"
  ]
}
=================

=== Geospatial data resources
This standard does not specify how geospatial data resources are exposed in the API and if they can be retrieved as geospatial data (e.g. feature items). For example http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] includes the definition of collections and each collection is available in the /collections/{collectionId} path. OGC API - Common will provide a similar mechanism. Other paths in the API could also give access to geospatial data resources.

NOTE: The concept of geospatial data resource path substitutes the concept of "layer" in WMTS 1.0 but it is intended to give a better integration between data visualization and data access.

include::requirements/geodata-tilesets/REQ_desc-links.adoc[]

For example, an implementation of the http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core] returns a list of links that include geospatial aspects for each geospatial data resource in the /collections/{collectionId} path. OGC API  - Common is expected to provide a similar mechanism. In the JSON response, the array `links` is the place for adding a resource reference to the 'tiles' description.

.Fragment of a collection with a links array with one item of the array pointing to a tilesets.
=================
[source,JSON]
[
  ...
  {
    "id": "buildings",
    "title": "Buildings in the city of Bonn",
    "description": "This collection contains buildings",
    "attribution": "OpenStreetMap",
    "extent": {
      ...
    }
    "links": [
      ...
      {
        "href": "http://data.example.com/collections/buildings/tiles/WebMercatorQuad",
        "rel": "self",
        "type": "application/json",
      }
    ]
  }
  ...
]
=================

include::recommendations/geodata-tilesets/REC_desc-links.adoc[]

=== Geospatial data resources tilesets list
The geospatial data resource tilesets operation provides essential tileset metadata and links to tilesets resources allowing to request tiles from the resource.

==== Tilesets path

include::requirements/geodata-tilesets/REQ_operation.adoc[]

This standard does not specify the need for any additional query parameter in the GET request.

==== Response
A successful response to a geospatial data tilesets request is a list of tilesets as defined by the tilesets list conformance class.

=== A tile from a geospatial data resource
A tile resource is a fragment of a larger single geospatial data resource that is spatially constrained at the boundaries of the selected tile in a tile matrix set.
Details of the operation are described in the core conformance class.
