[[rc_geospatialdata-selection]]
== Requirement Class "Geo Data Resource Selection"

=== Overview

[[tiles-geodata-resource-selection-overview]]

include::requirements/requirements_class_geodata-selection.adoc[]

It will define how to include a query parameter to subsets of the dataset (e.g. which geospatial data resources are involved in the creation tiles.

**TBD**

**End of TBD**

=== General
include::recommendations/geodata-selection/REC_api-common.adoc[]

This building block stays flexible and does not require implementation OGC API - Common, allowing for other API architectures outside the OGC API framework to adopt it. However, a server under the OGC APIs is expected to implement OGC API - Common. If so, in practice, this means that the landing page and the conformance page follow OGC API - Common core and collections requirement classes when used. Temporarily, it is also possible to combine this building block with http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] that is not tied to OGC API - Common.

=== Declaration of conformance classes

To support "generic" clients that want to access multiple OGC API standards and extensions - and not "just" a specific API / server, the API has to declare the requirements classes it implements and conforms to.

==== Response

The conformance page mainly consists of a list of links.

include::requirements/geodata-selection/REQ_conformance-success.adoc[]

If the server declares also conformity to OGC API - Common or to http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0], then it has to consider the OGC API - Common requirements for declaring conformance, i.e. the use of a the conformance page. In the JSON format the conformance page is an array of links following the link schema defined in the OGC API - Common or in http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0]. Below is an example fragment of a conformance information page of an API conformant to OGC API - Common and OGC API - Tiles.

[[ConformancePageDataSelection]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset"
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tilesets"
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/dataset-tilesets"
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset/geodata-selection"
  ]
}
=================

=== Tiles
The Tilesets have information on how to retrieve a single tile representing a piece of information in the dataset in the way explained in the tileset class

==== Operation
The operation for retrieving dataset-tilesets is defined in the geodata-selection class. By default, the  geospatial data resources included in the dataset-tiles is undefined but it is supposed to represent the dataset. This class adds a mechanism to select the geospatial data resources that are going to be used to create the tiles. In practice this give use the capability to create tiles from more than one geospatial data resources selectively.

==== Parameter Resources
include::requirements/geodata-selection/REQ_query-geodata.adoc[]

==== Error conditions

If the value of the parameter `geodata` contains a resource id of URI that does not exist on the API, the status code of the response is 404.

If the value of the parameter `geodata` has a wrong format or combines one of more geospatial data resources that are not compatible with the `tileMatrixSetId` value, the status code of the response is 500.
