[[rc_datasetTileSets]]
== Requirement Class "Dataset Tile Sets"

=== Overview

[[tiles-dataset-tiles-overview]]

include::requirements/requirements_class_dataset-tilesets.adoc[]

This conformance class defines a mechanism to retrieve a list of tilesets for a dataset (a.k.a., a root resource) which may contain multiple geospatial data resources. It is used in conjunction with <<rc_tileSets-list>> that specifies the response to this GET request.

Combined with the <<rc_collections-selection>> conformance class, it is also possible to select specific geospatial data resources (collections) to be combined and retrieved as tiles. For retrieving the list of tilesets for only one collection use the <<rc_geoDataResourceTileSets>>

If an Web API offers several geospatial data resources for a dataset, it may limit the number of collections that can be retrieved together, and/or provide a limited subset of the collections by default.

=== General
include::recommendations/dataset-tilesets/REC_api-common.adoc[]

This building block stays flexible and does not require implementation OGC API - Common - Part 1,
allowing for other Web API architectures outside the OGC API framework to adopt it.
However, a server under the OGC APIs is expected to implement OGC API - Common - Part 1.
If so, in practice, this means that the landing page and the conformance page follow OGC API - Common core requirement classes when used.
Temporarily, it is also possible to combine this building block with http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] that is not tied to OGC API - Common.

=== Web API landing page

The landing page provides links to start exploring the resources offered by the Web API. It mainly consists of a list of links to root resources. This standard extension requires a new link in the landing page for getting a description of the URL that allows for retrieving tiles of the resources in the dataset

==== Response

include::requirements/dataset-tilesets/REQ_landingpage.adoc[]

In the landing page, in JSON format, the links follow the link schema defined in the OGC API - Common or in OGC API - Features v1. Below you can find an example fragment of the response to an OGC API - Tiles landing page showing the link to dataset tilesets.

[[landingPageTilesRoot]]
.Web API Landing Page fragment that advertises dataset tilesets
=================
[source,JSON]
----
{
  "links": [
    ...,
    {
       "href": "http://data.example.org/tiles",
       "rel": "http://www.opengis.net/def/rel/ogc/1.0/tilesets-vector",
       "type": "application/json",
       "title": "List of available tilesets for the dataset",
    }
  ]
}
----
=================

include::recommendations/dataset-tilesets/REC_landingpage.adoc[]

=== Declaration of conformance classes

==== Response

The conformance page mainly consists of a list of URIs to conformance classes.

include::requirements/dataset-tilesets/REQ_conformance-success.adoc[]

On the conformance page (typically in JSON format) the list of URIs follows the schema defined in the OGC API - Common draft specification. The following is an example fragment from the response to an OGC API - Tiles conformance information page showing the support for dataset tilesets

[[ConformancePageDatasetTilesets]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tilesets-list",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/dataset-tilesets"
  ]
}
=================

=== Dataset tilesets
The dataset tilesets operation provides essential tileset metadata and links to tilesets resources allowing to request tiles from the dataset.

==== Operation

include::requirements/dataset-tilesets/REQ_operation.adoc[]

The request of this operation has no parameters.

==== Response
A successful response to a dataset tilesets list request is a list of tilesets as defined by the tilesets list conformance class.

=== Tiles
The Tileset class have information on how to retrieve a single tile representing a piece of information in the dataset in the way explained in the core and tileset classes

==== Response
The response is expected to represent the dataset as a whole. In a Web API providing access to a complex dataset formed by several geospatial data resources, there are reasons for being selective in the amount of information included. This can be achieved by applying a manual filter currently described in a OGC API - Tiles - Part 1 or as an automatic decision by the server side.

include::recommendations/dataset-tilesets/REC_geodata-selection.adoc[]

include::recommendations/dataset-tilesets/PER_geodata-selection.adoc[]
