[[rc_geoDataResourceTileSets]]
== Requirement Class "Geo Data Resource TileSets"

=== Overview

[[tiles-geoDataResourceTileSets-overview]]

include::requirements/requirements_class_geodata-tilesets.adoc[]

This conformance class assumes that data is organized into one or more geospatial data resources
(e.g., the "collections" http://docs.opengeospatial.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial data]).
Geospatial data resources are referenced using URIs.

It defines how to specify the a link to the list of tilesets containing a representation of this geospatial data resource (path). It is used in conjunction with <<rc_tileSets-list>> that specifies the response to this GET request.

=== General
include::recommendations/geodata-tilesets/REC_api-common.adoc[]

This building block depends on _OGC API - Part 2: Geospatial data_, but stays flexible and does not require implementation of OGC API - Common - Part 1,
allowing for other Web API architectures outside the OGC API framework to adopt it.
However, a server implementing other OGC APIs is expected to implement OGC API - Common - Part 1.
In practice, this means that the landing page and the conformance page follow OGC API - Common core requirement classes when used.
Temporarily, it is also possible to combine this building block with http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] that is not tied to OGC API - Common.

=== Geospatial data resources
This standard does not specify how geospatial data resources are exposed in the Web API and if they can be retrieved as geospatial data (e.g., feature items). For example http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core, version 1.0] includes the definition of collections and each collection is available in the /collections/{collectionId} path. OGC API - Common will provide a similar mechanism. Other paths in the Web API could also give access to geospatial data resources.

NOTE: The concept of geospatial data resource path substitutes the concept of "layer" in WMTS 1.0 but it is intended to give a better integration between data visualization and data access.

include::requirements/geodata-tilesets/REQ_desc-links.adoc[]

For example, an implementation of the http://www.opengis.net/doc/IS/ogcapi-features-1/1.0[OGC API - Features - Part 1: Core] returns a list of links that include geospatial aspects for each geospatial data resource in the /collections/{collectionId} path. OGC API  - Common is expected to provide a similar mechanism. In the JSON response, the array `links` is the place for adding a resource reference to the 'tiles' description.

.Fragment of a collection with a links array with one item of the array pointing to a tilesets.
=================
[source,JSON]
[
  ...
  {
    "id": "buildings",
    "title": "Buildings in the city of Bonn",
    "description": "This collection contains buildings",
    "attribution": "OpenStreetMap",
    "extent": {
      ...
    }
    "links": [
      ...
      {
        "href": "http://data.example.com/collections/buildings/tiles/WebMercatorQuad",
        "rel": "self",
        "type": "application/json",
      }
    ]
  }
  ...
]
=================

include::recommendations/geodata-tilesets/REC_desc-links.adoc[]

=== Geospatial data resources tilesets list
The geospatial data resource tilesets operation provides essential tileset metadata and links to tilesets resources allowing to request tiles from the resource.

==== Tilesets path

include::requirements/geodata-tilesets/REQ_operation.adoc[]

This standard does not specify the need for any additional query parameter in the GET request.

==== Response
A successful response to a geospatial data tilesets request is a list of tilesets as defined by the tilesets list conformance class.

=== A tile from a geospatial data resource
A tile resource is a fragment of a larger single geospatial data resource that is spatially constrained at the boundaries of the selected tile in a tile matrix set.
Details of the operation are described in the core conformance class.
