[[ats_tileset-description.adoc]]
////
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/tileset/description*
^|Test Purpose |Validate the content of a tileset description
^|Requirement |/req/tileset/description
^|Test Method |1. Validate that the tileset endpoint SHALL support negotiating an application/json response. In this case, a successful response of a HTTP GET for a specific tileset is encoded following the data model and JSON schema for tileset metadata, as defined by the 2D Tile Matrix Set and Tileset Metadata standard 2.0.

2. If the tileset endpoint also support negotiating an application/xml response,  validate that a successful response of a HTTP GET for a specific tileset is encoded following the data model and XML schema for tileset metadata, as defined by the 2D Tile Matrix Set and Tileset Metadata standard 2.0.

3. If the tileset uses a TileMatrixSet registered in a TileMatrixSet registry (e.g. OGC NA), validate that the `tileMatrixSetURI` property links to the registered TileMatrixSet (e.g. `http://www.opengis.net/def/tilematrixset/{tileMatrixSet}`).

4. Validate that the links property includes a link to the TileMatrixSet definition with relation type `http://www.opengis.net/def/rel/ogc/1.0/tiling-scheme` following the
https://github.com/opengeospatial/2D-Tile-Matrix-Set/blob/master/schemas/tms/2.0/json/tileMatrixSet.json[tile matrix set schema], as defined by the 2D Tile Matrix Set and Tileset Metadata standard 2.0.

5. Validate that the tileset metadata includes at least one templated link to individual tiles using the relation type `item`, and the template parameters
`{tileMatrix}`, and `{tileRow}` and `{tileCol}`. Those variables are to be substituted by their respective valid values to obtain the URL to a tile.

6. If a tiles link template is specific to a particular format, validate that contains the media type for that format in the `"type"` property. Otherwise, normal HTTP content type negotiation rules apply (`Accept:` header).

7. Validate that a property `templated` with a boolean `true` value is part of the link properties to indicate that the link needs to be processed to substitute the templated variables with valid values before being used as a URL to a tile.
|===
////


[abstract_test]
====
[%metadata]
identifier:: /conf/tileset/description
target:: /req/tileset/description
test-purpose:: Validate the content of a tileset description
+
--
1. Validate that the tileset endpoint SHALL support negotiating an application/json response. In this case, a successful response of a HTTP GET for a specific tileset is encoded following the data model and JSON schema for tileset metadata, as defined by the 2D Tile Matrix Set and Tileset Metadata standard 2.0.

2. If the tileset endpoint also support negotiating an application/xml response,  validate that a successful response of a HTTP GET for a specific tileset is encoded following the data model and XML schema for tileset metadata, as defined by the 2D Tile Matrix Set and Tileset Metadata standard 2.0.

3. If the tileset uses a TileMatrixSet registered in a TileMatrixSet registry (e.g. OGC NA), validate that the `tileMatrixSetURI` property links to the registered TileMatrixSet (e.g. `http://www.opengis.net/def/tilematrixset/{tileMatrixSet}`).

4. Validate that the links property includes a link to the TileMatrixSet definition with relation type `http://www.opengis.net/def/rel/ogc/1.0/tiling-scheme` following the
https://github.com/opengeospatial/2D-Tile-Matrix-Set/blob/master/schemas/tms/2.0/json/tileMatrixSet.json[tile matrix set schema], as defined by the 2D Tile Matrix Set and Tileset Metadata standard 2.0.

5. Validate that the tileset metadata includes at least one templated link to individual tiles using the relation type `item`, and the template parameters
`{tileMatrix}`, and `{tileRow}` and `{tileCol}`. Those variables are to be substituted by their respective valid values to obtain the URL to a tile.

6. If a tiles link template is specific to a particular format, validate that contains the media type for that format in the `"type"` property. Otherwise, normal HTTP content type negotiation rules apply (`Accept:` header).

7. Validate that a property `templated` with a boolean `true` value is part of the link properties to indicate that the link needs to be processed to substitute the templated variables with valid values before being used as a URL to a tile.
--
====
