[[per_core_tc-tile-encoding]]
////
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/core/tc-tile-encoding*
^|A |This draft specification does not impose any media type on the encoding of a response containing tiled feature data. For features the media type MAY be GeoJSON, Mapbox vector tiles or other format.
^|B |This draft specification does not impose any media type on the encoding of a response containing tiled coverage data. For coverages it MAY be a GeoTIFF, netCDF or other format.
^|C |This draft specification does not impose any media type on the encoding of a map tile response. For maps it MAY be a JPEG, PNG or other format.
|===
////

[permission]
====
[%metadata]
identifier:: /per/core/tc-core-tile-encoding
part:: This standard does not impose any media type on the encoding of a response containing tiled feature data. For features, the media type MAY be GeoJSON, Mapbox Vector Tiles or other format.
part:: This standard does not impose any media type on the encoding of a response containing tiled coverage data. For coverages, it MAY be a GeoTIFF, netCDF or other format.
part:: This standard does not impose any media type on the encoding of a map tile response. For maps, it MAY be JPEG, PNG or other format.
====
