[[ats_oas30_completeness]]
////
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/oas30/completeness*
^|Test Purpose |Validate OpenAPI completeness and consistency
^|Requirement |/req/oas30/completeness
^|Test Method |1. Validate that OpenAPI definition describes all tileset, tilesets list and tile resources provided by the API instance.

2. Validate that the OpenAPI paths are consistent with the links provided by the landing page, tileset and tilesets list resources.

3. Validate that the OpenAPI paths provides the description of the parameters that the tileset and tile resources need to operate as specified in the corresponding conformance classes.
|===
////


[abstract_test]
====
[%metadata]
identifier:: /conf/oas30/completeness
target:: /req/oas30/completeness
test-purpose:: Validate OpenAPI completeness and consistency
+
--
1. Validate that OpenAPI definition describes all tileset, tilesets list and tile resources provided by the API instance.

2. Validate that the OpenAPI paths are consistent with the links provided by the landing page, tileset and tilesets list resources.

3. Validate that the OpenAPI paths provides the description of the parameters that the tileset and tile resources need to operate as specified in the corresponding conformance classes.
--
====
