[[ats_core_core_tc-success]]
////
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/core/tc-success*
^|Test Purpose |Validate that a successful execution with data responds with a HTTP status code `200`, the format is consistent with the requested and the elements represented in the tile are the ones present in the geographical area.
^|Requirement |/req/core/tc-success
^|Test Method |1. Validate that a successful execution of the operation with content responds with a HTTP status code `200`.

2. Validate that the content of that response is consistent with the format requested via HTTP content negotiation and represents elements inside or intersecting with the spatial extent of the geographical area of the tile identified by the tile matrix, tile row and tile column of the tileset's tile matrix set.
|===
////

[abstract_test]
====
[%metadata]
identifier:: /conf/core/tc-success
target:: /req/core/tc-success
test-purpose:: Validate that a successful execution with data responds with a HTTP status code `200`, the format is consistent with the requested and the elements represented in the tile are the ones present in the geographical area.
test-method::
+
--
1. Validate that a successful execution of the operation with content responds with a HTTP status code `200`.

2. Validate that the content of that response is consistent with the format requested via HTTP content negotiation and represents elements inside or intersecting with the spatial extent of the geographical area of the tile identified by the tile matrix, tile row and tile column of the tileset's tile matrix set.
--
====
