[[ats_core_core_tc-error]]
////
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/core/tc-error*
^|Test Purpose |Validate that the request of tile that is out-of-range or empty, responds the right content
^|Requirement |/req/core/tc-error
^|Test Method |1.  If the path parameter values `tileMatrix`, `tileRow`, `tileCol` for a tile request are out-of-range (outside the tile matrix set or tile matrix set limits of the resource), validate that the HTTP response is a status code `404` or a `400`.

2. If the tile has no content due to lack of data in the area, but is within the data resource's tile matrix sets and tile matrix sets limits, validate that the HTTP response is a status code either 204 (indicating an empty tile with no content) or a 200 with the content of a blank response compatible with the requested media type (which may or may not be zero bytes long, depending on the output format; e.g., a 0 byte file if valid for the requested format, or a PNG with internal headers and no "pixels").
|===
////

[abstract_test]
====
[%metadata]
identifier:: /conf/core/tc-error
target:: /req/core/tc-error
test-purpose:: Validate that the request for a tile that is out-of-range or empty, responds with the right content
test-method::
+
--
1.  If the path parameter values `tileMatrix`, `tileRow`, `tileCol` for a tile request are out-of-range (outside the tile matrix set or tile matrix set limits of the resource), validate that the HTTP response is a status code `404` or a `400`.

2. If the tile has no content due to lack of data in the area, but is within the data resource's tile matrix sets and tile matrix sets limits, validate that the HTTP response is a status code either 204 (indicating an empty tile with no content) or a 200 with the content of a blank response compatible with the requested media type (which may or may not be zero bytes long, depending on the output format; e.g., a 0 byte file if valid for the requested format, or a PNG with internal headers and no "pixels").
--
====
