== Requirement Class "Tiles Tile Matrix Set"

=== Overview

[[tiles-tmxs-overview]]

include::requirements/tiles/requirements_class_tmxs.adoc[]

The _tiles core_ requirements class states that the service can support the eight TileMatrixSets defined in the Annex D.1 of the OGC 17-083r2 standard by mentioning their identifiers without the need to describe them. This requirement class acts as and extension of the core requirements class that adds all the necessary elements to support other TileMatrixSets by adding a mechanism to fully describe TileMatrixSets that are specific to the API instance.

The entry point is a `Landing page` (path `/`).

The `Landing page` provides links to:

* the `API definition` (path `/api`, link relation `service-desc`),
* the `Conformance declaration` (path `/conformance`, link relation `conformance`), and
* the `Collections` (path `/collections`, link relation `data`).
* the `TileMatrixSets` (path `/tileMatrixSets`, link relation `tiling-schemes`).

=== API landing page

The landing page provides links to start exploring the resources offered by the API. It mainly consists in a list of links. The core of this draft specification does not add anything to the links required by OGC API - Common. This extension for TileMatrixSet requires new links for TileMatrixSets on top of the common ones.

==== Response

include::requirements/tiles/tmxs/REQ_root-success.adoc[]

In the landing page, in JSON format, the links follow the link schema defined in the OGC API - Common. The following is an example fragment of the response to an OGC API - Tiles landing page.

[[landingPageTilesTmxs]]
.API Landing Page fragment with links to TileMatrixSet descriptions
=================
[source,JSON]
----
{
  links: [
    ...,
    {
      "href": "http://data.example.org/tileMatrixSet?f=json",
      "rel": "tiling-schemas",
      "type": "application/json",
      "title": "List of tileMatrixSets implemented by this API in JSON",
    },
    {
      "href": "http://data.example.org/tileMatrixSet?f=html",
      "rel": "tiling-schemas",
      "type": "text/html",
      "title": "List of tileMatrixSets implemented by this API in HTML",
    }
  ]
}
----
=================

=== Declaration of conformance classes

==== Response

The conformance page mainly consists of a list of links. OGC API - Common already requires some links for the core and collections requirements classes

include::requirements/tiles/tmxs/REQ_conformance-success.adoc[]

In the conformance page (typically in JSON format) the links follow the link schema defined in the OGC API - Common. The following is an example fragment of the response to an OGC API tiles conformance information page.

[[ConformancePageTilesTmxs]]
.Conformance Information Page fragment
=================
[source,JSON]
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tmxs",
    "http://www.opengis.net/spec/tilematrixset/1.0/conf/tilematrixset2d",
    "http://www.opengis.net/spec/tilematrixset/1.0/conf/json-tilematrixset2d",
    "http://www.opengis.net/spec/tilematrixset/1.0/conf/tilematrixsetlimits2d",
    "http://www.opengis.net/spec/tilematrixset/1.0/conf/json-tilematrixsetlimits2d"
  ]
}
=================

=== TileMatrixSets

The TileMatrixSets operation retrieves links to the descriptions of the tile matrix sets supported by the API instance in addition to the eight TileMatrixSets defined in the Annex D.1 of the OGC 17-083r2 standard.

==== Operation
include::requirements/tiles/tmxs/REQ_tilematrixsets-op.adoc[]

==== Response
include::requirements/tiles/tmxs/REQ_tilematrixsets-success.adoc[]

[[TileMatrixSetsResponseSchema]]
.Schema for the TileMatrixSets resource
=================
[source,YAML]
  type: object
  required:
    - tileMatrixSets
  properties:
    tileMatrixSets:
      type: array
      items:
        $ref: 'https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-common/1.0.0#/components/schemas/id-link'
=================

[[TileMatrixSetsResponseCommonSchema]]
.Schema for id-link from OGC API - Common used in TileMatrixSets resource.
=================
[source,YAML]
id-link:
  type: object
  description: |-
    Reusable object that contains an id to a resource and links where the object is described or a representation retrieved. Typically it is useful for paths like `/resources` and `/resources/{resourceId}`.   `/resources` will respond an array of id-link listing the `resourceId` and the links to get it. /collections and /collections/{collectionId} is an exception to this pattern.
    The fact that `links` is an array can be used to advertise the same object representation in different formats.
  required:
    - id
    - links
  properties:
    id:
      type: string
    title:
      type: string
    links:
      type: array
      minItems: 1
      items:
        $ref: '#/components/schemas/link'
=================

[[TileMatrixSetsResponseExample]]
.Example for the TileMatrixSets resource
=================
[source,JSON]
{
  "tileMatrixSets": [
    {
      "id": "MyWebMercatorQuad",
      "title": "My Google Maps Compatible for the World",
      "links": [
        {
          "href": "https://data.example.org/tileMatrixSet/MyWebMercatorQuad",
          "rel": "item",
          "type": "application/json"
        }
      ]
    }
  ]
}
=================

=== TileMatrixSet

The TileMatrixSet operation retrieves the full description of a tile matrix set supported by the API instance following the schema described in the OGC 17-083r2 standard.

==== Operation
include::requirements/tiles/tmxs/REQ_tilematrixset-op.adoc[]

==== Response
include::requirements/tiles/tmxs/REQ_tilematrixset-success.adoc[]

include::recommendations/tiles/tmxs/REC_tilematrixset-response.adoc[]

[[TileMatrixSetResponseExample]]
.Fragment of a TileMatrixSet resource
=================
[source,JSON]
{
  "title": "Google Maps Compatible for the World",
  "abstract": "The most common TileMatrixSet, used in most of the main IT map browsers. It was initially popularized by Google Maps",
  "identifier": "WebMercatorQuad",
  "supportedCRS": "http://www.opengis.net/def/crs/EPSG/0/3857",
  "wellKnownScaleSet": "http://www.opengis.net/def/wkss/OGC/1.0/GoogleMapsCompatible",
  "tileMatrix": [
    ...
    {
      "title": "Google Maps Compatible for the World zoom level 3",
      "abstract": "Google Maps Compatible zoom level 3 that is equivalent to a scale of 1:69885283.00358972 and has 19567.87924100512 meters of pixel size in the equator",
      "identifier": "3",
      "scaleDenominator": 69885283.00358972,
      "topLeftCorner": [
        -20037508.3427892,
        20037508.3427892
      ],
      "tileWidth": 256,
      "tileHeight": 256,
      "matrixHeight": 8,
      "matrixWidth": 8
    }
    ...
  ]
}
=================


=== Tiles
The requirements class described in this section also defines and extra element _limits_ in the tiles metadata returned by a successful /collection/{collectionId}/tiles request that can be used for the API instance to document limitations in the scales and extents supported in the context of the tile matrix set that is defined in a more unrestricted way.

==== Collection extra properties

include::requirements/tiles/tmxs/REQ_stc-limits.adoc[]

[[TilesLimitsResponseExample]]
.Fragment of a Tiles resource with limits
=================
[source,JSON]
{
  "tileMatrixSetLinks": [
    {
      "type": "tileMatrixSetLink",
      "tileMatrixSet": "http://www.opengis.net/def/tilematrixset/OGC/1.0/WebMercatorQuad",
      "tileMatrixSetLimits": [
        {
          "type": "tileMatrixSetLimits",
          "tileMatrix": "5",
          "minTileRow": 0,
          "maxTileRow": 1,
          "minTileCol": 3,
          "maxTileCol": 4
        }
      ]
    }
  ],
  ...
  "links": [
    ...
    {
     "href": "http://data.example.com/collections/buildings/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}.png",
     "rel": "item",
     "type": "image/png",
     "$$ref": "https://api.swaggerhub.com/domains/UAB-CREAF/ogc-api-tiles/1.0.0#/components/examples/link-tiles-tile"
   }
   ...
  ]
}
=================
