[[req_xml_content]]
////
[width="90%",cols="2,6a"]
|===
^|*Requirement {counter:req-id}* |*/req/xml/content*
^|A|Every request to a TileSets list or TileSet resource which:

. Receives a `200`-response
. with the `Content-Type` header set to `application/xml`

SHALL include, or link to, a payload encoded according to the  link:https://www.w3.org/TR/xml/[Extensible Markup Language (XML) 1.0]
^|B|The payload for these responses SHALL conform with the XML Schema specified for the resource in the OGC 17-083r4: OGC Two Dimensional Tile Matrix Set and Tile Set Metadata.
|===
////

[requirement,label="/req/xml/content",identifier="/req/xml/content"]
====

[.component,class=part]
--
Every request to a TileSets list or TileSet resource which:

. Receives a `200`-response
. with the `Content-Type` header set to `application/xml`

SHALL include, or link to, a payload encoded according to the  link:https://www.w3.org/TR/xml/[Extensible Markup Language (XML) 1.0]
--

[.component,class=part]
--
The payload for these responses SHALL conform with the XML Schema specified for the resource in the OGC 17-083r4: OGC Two Dimensional Tile Matrix Set and Tile Set Metadata.
--
====
