[[ats_dataset-tilesets-landingpage]]
////
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/dataset-tilesets/landingpage*
^|Test Purpose |Validate that it is possible to retrieve the tilesets list for the dataset
^|Requirement |/req/dataset-tilesets/landingpage
^|Test Method |1.- If the API has mechanism to expose root resources (e.g., a landing page), validate that the API advertises at least one URIs to retrieve tilesets list provided by this service with a link having a `rel` value: `http://www.opengis.net/def/rel/ogc/1.0/tilesets-vector`,  `http://www.opengis.net/def/rel/ogc/1.0/tilesets-map` or `http://www.opengis.net/def/rel/ogc/1.0/tilesets-coverage`.
|===
////

[abstract_test]
====
[%metadata]
identifier:: /conf/dataset-tilesets/landingpage
target:: /req/dataset-tilesets/landingpage
test-purpose:: Validate that it is possible to retrieve the tilesets list for the dataset
test-method::
+
--
1. If the API has a mechanism to expose root resources (e.g., a landing page), validate that the API advertises at least one URI for retrieving a tilesets list that is provided by this service with a link having a `rel` value: `http://www.opengis.net/def/rel/ogc/1.0/tilesets-vector`,  `http://www.opengis.net/def/rel/ogc/1.0/tilesets-map` or `http://www.opengis.net/def/rel/ogc/1.0/tilesets-coverage`.
--
====
