[[ats_jpeg_content]]
////
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/jpeg/content*
^|Test Purpose |Validate the particularities of a JPEG response
^|Requirement |/req/jpeg/content
^|Test Method |1. Validate that every 200-response of the server with the media type image/jpeg contains a JPEG document representing only one tile

2. Validate that the colors of the JPEG represents coverage values or geospatial features in the tile.

3. Validate that all tiles representing parts of the same resource or resources using the same style are following the same portrayal rules
|===
////

[abstract_test]
====
[%metadata]
identifier:: /conf/jpeg/content
target:: /req/jpeg/content
test-purpose:: Validate the particularities of a JPEG response
test-method::
+
--
1. Validate that every 200-response of the server with the media type image/jpeg contains a JPEG document representing only one tile.

2. Validate that the colors of the JPEG represent coverage values or geospatial features in the tile.

3. Validate that all tiles representing parts of the same resource or resources using the same style are following the same portrayal rules.
--
====
