[[ats_mvt_content]]
////
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/mvt/content*
^|Test Purpose |Validate the particularities of a Mapbox Vector Tiles response
^|Requirement |/req/mvt/content
^|Test Method |1. Validate that every 200-response of the server with the media type application/vnd.mapbox-vector-tile contains a Mapbox Vector Tile document representing only one tile.

2. Validate that a feature contains a geometry field. Validate that a feature contains a type field as described in the Geometry Types section.

3. Validate that the grid space for the MVT coordinates maps linearly to the coordinates in the tile extent expressed in the Tileset CRS unless a _prior arrangement_ applies to use an alternative CRS; and in this case the linear mapping is done to the alternative CRS and not with the Tileset CRS. For example, an extension could negotiate another CRS for coordinates with a query parameter. In particular the 0,0 coordinate in the MVT maps to the top-left corner of the tile. The bottom-right corner of the tile corresponds the bottom-right corner of the MVT grid.
|===
////

[abstract_test]
====
[%metadata]
identifier:: /conf/mvt/content
target:: /req/mvt/content
test-purpose:: Validate the particularities of a Mapbox Vector Tiles response
+
--
1. Validate that every 200-response of the server with the media type application/vnd.mapbox-vector-tile contains a Mapbox Vector Tile document representing only one tile.

2. Validate that a feature contains a geometry field. Validate that a feature contains a type field as described in the Geometry Types section.

3. Validate that the grid space for the MVT coordinates maps linearly to the coordinates in the tile extent expressed in the Tileset CRS unless a _prior arrangement_ applies to use an alternative CRS; and in this case the linear mapping is done to the alternative CRS and not with the Tileset CRS. For example, an extension could negotiate another CRS for coordinates with a query parameter. In particular the 0,0 coordinate in the MVT maps to the top-left corner of the tile. The bottom-right corner of the tile corresponds the bottom-right corner of the MVT grid.
--
====
