[[per_tilesets-list_api]]
////
[width="90%",cols="2,6a"]
|===
^|*Permission {counter:per-id}* |*/per/tilesets-list/tilesets-api*
^|A |An API document can advertise a single resource path (expressed as a URI template) to get multiple tilesets.
^|B |This URI template will use the `{tileMatrixSetId}` variable. The `{tileMatrixSetId}` variable will be interpreted as one of TileMatrixSet identifiers supported by the resource. In other words, it represents all the TileMatrixSets supported by the resource. Note that a `{tileMatrixSetId}` variable must NOT be used in the templated links of the tileset metadata.
|===
////

[permission]
====
[%metadata]
identifier:: /per/tilesets-list/tilesets-api
part:: An API document can advertise a single resource path (expressed as a URI template) to get multiple tilesets.
part:: This URI template will use the `{tileMatrixSetId}` variable. The `{tileMatrixSetId}` variable will be interpreted as one of TileMatrixSet identifiers supported by the resource. In other words, it represents all the TileMatrixSets supported by the resource. Note that a `{tileMatrixSetId}` variable must NOT be used in the templated links of the tileset metadata.
====
