[[ats_tilesets-tileset-links]]
////
[width="90%",cols="2,6a"]
|===
^|*Abstract Test {counter:ats-id}* |*/conf/tilesets-list/tileset-links*
^|Test Purpose |Validate that the content of a tileset list
^|Requirement |/req/tilesets-list/tileset-links
^|Test Method |1. Validate that the API SHALL supports a GET operation on a `.../tiles` path returning a list of available tilesets

2. Validate that a successful response of a HTTP GET consists of a list of available tilesets each element containing a subset of the tileset metadata (as defined by the 2D Tile Matrix Set and Metadata standard), consisting of: `dataType, `crs`, a link to the tileset (with rel: self), a link to the TileMatrixSet defintion (with rel: `http://www.opengis.net/def/rel/ogc/1.0/tiling-scheme`) and `tileMatrixSetURI` (if the TMS is available in a registry).

3. Validate that each element of that list includes a link to a resource providing the full version of the tileset metadata, using link relation `self`.

4. Validate that the tileset-list endpoint supports negotiating an application/json response. In this case, validate that each tileset in the successful response of a HTTP GET is encoded following the data model and JSON schema for tileset metadata, as defined by the 2D Tile Matrix Set and Tileset Metadata standard 2.0.

5. If the tileset-list endpoint also supports negotiating an application/xml response, validate that each tileset in the successful response of a HTTP GET is encoded following the data model and XML schema for tileset metadata, as defined by the 2D Tile Matrix Set and Tileset Metadata standard 2.0.

6. Validate that the tileset is available as a URI that is composed by three parts: The first part is the URL of the geospatial resource (e.g., '.../map') followed by the word '/tiles', and finally followed by the id of the tile matrix set supported.
|===
////


[abstract_test]
====
[%metadata]
identifier:: /conf/tilesets-list/tileset-links
target:: /req/tilesets-list/tileset-links
test-purpose:: Validate that the content of a tileset list
test-method::
+
--
1. Validate that the API SHALL supports a GET operation on a `.../tiles` path returning a list of available tilesets

2. Validate that a successful response of a HTTP GET consists of a list of available tilesets each element containing a subset of the tileset metadata (as defined by the 2D Tile Matrix Set and Metadata standard), consisting of: `dataType, `crs`, a link to the tileset (with rel: self), a link to the TileMatrixSet defintion (with rel: `http://www.opengis.net/def/rel/ogc/1.0/tiling-scheme`) and `tileMatrixSetURI` (if the TMS is available in a registry).

3. Validate that each element of that list includes a link to a resource providing the full version of the tileset metadata, using link relation `self`.

4. Validate that the tileset-list endpoint supports negotiating an application/json response. In this case, validate that each tileset in the successful response of a HTTP GET is encoded following the data model and JSON schema for tileset metadata, as defined by the 2D Tile Matrix Set and Tileset Metadata standard 2.0.

5. If the tileset-list endpoint also supports negotiating an application/xml response, validate that each tileset in the successful response of a HTTP GET is encoded following the data model and XML schema for tileset metadata, as defined by the 2D Tile Matrix Set and Tileset Metadata standard 2.0.

6. Validate that the tileset is available as a URI that is composed by three parts: The first part is the URL of the geospatial resource (e.g., '.../map') followed by the word '/tiles', and finally followed by the id of the tile matrix set supported.
--
====
